-- migrations/12_beauty_category_tree_schema.sql
-- Beauty 3-level category tree, part 1 of 8 — RUN THIS FILE FIRST, ALONE.
-- Files 13..19 (one per department) depend on the columns this adds.
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here. Idempotent, safe to re-run.

ALTER TABLE beauty_categories
  ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES beauty_categories(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS level     INT NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_beauty_categories_parent ON beauty_categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_beauty_categories_level  ON beauty_categories (level);

-- Retire the old two-level starter seed (only rows with no products attached).
DELETE FROM beauty_categories
  WHERE slug IN ('cleansers', 'serums', 'moisturizers', 'suncare', 'face-makeup', 'lip-makeup', 'eye-makeup', 'fragrance', 'brushes', 'devices')
    AND id NOT IN (SELECT category_id FROM beauty_products WHERE category_id IS NOT NULL);
