-- migrations/17_beauty_category_tree_electrical.sql
-- Beauty 3-level category tree, part 6 of 8 — run AFTER
-- 12_beauty_category_tree_schema.sql, in any order relative to the other
-- department files (this one only references its own rows).
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here. Idempotent, safe to re-run.
--
-- Verify after running all 8 files:
--   SELECT level, COUNT(*) FROM beauty_categories GROUP BY level ORDER BY level;
--   SELECT slug, name_fa FROM beauty_categories WHERE parent_id IS NULL ORDER BY sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('electrical', NULL, 1, 'electrical', 'Лавозими барқӣ', 'Электроприборы', 'Electrical Appliances', 'لوازم برقی', 'zap', 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('elec-shaving', (SELECT id FROM beauty_categories WHERE slug='electrical'), 2, 'electrical', 'Ислоҳи рӯй ва бадан', 'Бритьё и эпиляция', 'Shaving & Epilation', 'اصلاح صورت و بدن', 'edit', 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('epilator', (SELECT id FROM beauty_categories WHERE slug='elec-shaving'), 3, 'electrical', 'Мӯйканак', 'Эпилятор', 'Epilator', 'اپیلاتور', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('electric-threading', (SELECT id FROM beauty_categories WHERE slug='elec-shaving'), 3, 'electrical', 'Бандандози барқӣ', 'Электрический тридинг', 'Electric Threading', 'بندانداز برقی', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hair-clipper', (SELECT id FROM beauty_categories WHERE slug='elec-shaving'), 3, 'electrical', 'Мошини ислоҳ', 'Машинка для стрижки', 'Hair Clipper', 'ماشین اصلاح', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('trimmer', (SELECT id FROM beauty_categories WHERE slug='elec-shaving'), 3, 'electrical', 'Мӯзани гӯш, бинӣ ва абрӯ', 'Триммер', 'Nose, Ear & Brow Trimmer', 'موزن گوش، بینی و ابرو', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('elec-hair-styling', (SELECT id FROM beauty_categories WHERE slug='electrical'), 2, 'electrical', 'Ҳолатдиҳандаҳои барқии мӯй', 'Электростайлинг волос', 'Electric Hair Styling', 'حالت‌دهنده‌های برقی مو', 'wind', 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hair-dryer', (SELECT id FROM beauty_categories WHERE slug='elec-hair-styling'), 3, 'electrical', 'Сешвор', 'Фен', 'Hair Dryer', 'سشوار', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hair-straightener', (SELECT id FROM beauty_categories WHERE slug='elec-hair-styling'), 3, 'electrical', 'Утуи мӯй', 'Выпрямитель', 'Hair Straightener', 'اتو مو', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('curling-iron', (SELECT id FROM beauty_categories WHERE slug='elec-hair-styling'), 3, 'electrical', 'Фери мӯй', 'Плойка', 'Curling Iron', 'فر مو', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hot-brush', (SELECT id FROM beauty_categories WHERE slug='elec-hair-styling'), 3, 'electrical', 'Бурси гармӣ', 'Термощётка', 'Hot Brush', 'برس حرارتی', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('elec-skincare', (SELECT id FROM beauty_categories WHERE slug='electrical'), 2, 'electrical', 'Асбоби барқии нигоҳубини пӯст', 'Электроприборы для кожи', 'Electric Skincare', 'ابزار برقی مراقبت از پوست', 'sparkles', 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('electric-face-brush', (SELECT id FROM beauty_categories WHERE slug='elec-skincare'), 3, 'electrical', 'Фейс браши барқӣ', 'Электрощётка для лица', 'Electric Face Brush', 'فیس براش برقی', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('elec-nail', (SELECT id FROM beauty_categories WHERE slug='electrical'), 2, 'electrical', 'Асбоби барқии нохун', 'Электроприборы для ногтей', 'Electric Nail Care', 'ابزار برقی مراقبت از ناخن', 'settings', 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('manicure-machine', (SELECT id FROM beauty_categories WHERE slug='elec-nail'), 3, 'electrical', 'Дастгоҳи маникюр ва педикюр', 'Аппарат для маникюра', 'Manicure & Pedicure Machine', 'دستگاه مانیکور و پدیکور', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('elec-oral', (SELECT id FROM beauty_categories WHERE slug='electrical'), 2, 'electrical', 'Асбоби барқии даҳон ва дандон', 'Электроприборы для полости рта', 'Electric Oral Care', 'ابزار برقی مراقبت از دهان و دندان', 'sparkles', 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('electric-toothbrush', (SELECT id FROM beauty_categories WHERE slug='elec-oral'), 3, 'electrical', 'Чӯткаи дандони барқӣ', 'Электрическая зубная щётка', 'Electric Toothbrush', 'مسواک برقی', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('toothbrush-head', (SELECT id FROM beauty_categories WHERE slug='elec-oral'), 3, 'electrical', 'Сари иловагии чӯткаи барқӣ', 'Насадки для щётки', 'Toothbrush Heads', 'سری یدک مسواک برقی', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('elec-health', (SELECT id FROM beauty_categories WHERE slug='electrical'), 2, 'electrical', 'Асбоби саломатӣ', 'Приборы для здоровья', 'Health Devices', 'ابزار سلامت', 'zap', 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('air-purifier', (SELECT id FROM beauty_categories WHERE slug='elec-health'), 3, 'electrical', 'Дастгоҳи тозакунии ҳаво', 'Очиститель воздуха', 'Air Purifier', 'دستگاه تصفیه هوا', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;
