-- migrations/18_beauty_category_tree_fashion.sql
-- Beauty 3-level category tree, part 7 of 8 — run AFTER
-- 12_beauty_category_tree_schema.sql, in any order relative to the other
-- department files (this one only references its own rows).
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here. Idempotent, safe to re-run.
--
-- Verify after running all 8 files:
--   SELECT level, COUNT(*) FROM beauty_categories GROUP BY level ORDER BY level;
--   SELECT slug, name_fa FROM beauty_categories WHERE parent_id IS NULL ORDER BY sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('fashion', NULL, 1, 'fashion', 'Мӯд ва фашн', 'Мода и фэшн', 'Fashion', 'مد و فشن', 'tag', 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('womens-accessories', (SELECT id FROM beauty_categories WHERE slug='fashion'), 2, 'fashion', 'Аксессуари занона', 'Женские аксессуары', 'Women''s Accessories', 'اکسسوری زنانه', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-accessories', (SELECT id FROM beauty_categories WHERE slug='fashion'), 2, 'fashion', 'Аксессуари мардона', 'Мужские аксессуары', 'Men''s Accessories', 'اکسسوری مردانه', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;
