-- migrations/19_beauty_category_tree_supplements.sql
-- Beauty 3-level category tree, part 8 of 8 — run AFTER
-- 12_beauty_category_tree_schema.sql, in any order relative to the other
-- department files (this one only references its own rows).
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here. Idempotent, safe to re-run.
--
-- Verify after running all 8 files:
--   SELECT level, COUNT(*) FROM beauty_categories GROUP BY level ORDER BY level;
--   SELECT slug, name_fa FROM beauty_categories WHERE parent_id IS NULL ORDER BY sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('supplements', NULL, 1, 'supplements', 'Мукаммали ғизоӣ ва доруӣ', 'БАДы и добавки', 'Dietary Supplements', 'مکمل غذایی و دارویی', 'pill', 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('vitamins', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Витамин ва минералҳо', 'Витамины и минералы', 'Vitamins & Minerals', 'ویتامین و مواد معدنی', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('fitness-supplement', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Мукаммали фитнес', 'Фитнес-добавки', 'Fitness Supplements', 'مکمل تناسب اندام', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('sports-supplement', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Мукаммали варзишӣ', 'Спортивные добавки', 'Sports Supplements', 'مکمل ورزشی', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('womens-supplement', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Мукаммали занона', 'Женские добавки', 'Women''s Supplements', 'مکمل بانوان', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('kids-supplement', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Мукаммали кӯдакон', 'Детские добавки', 'Kids'' Supplements', 'مکمل کودکان', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-supplement', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Мукаммали мардона', 'Мужские добавки', 'Men''s Supplements', 'مکمل آقایان', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('supplement-skin-hair', (SELECT id FROM beauty_categories WHERE slug='supplements'), 2, 'supplements', 'Мукаммали пӯст ва мӯй', 'Добавки для кожи и волос', 'Skin & Hair Supplements', 'مکمل پوست و مو', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;
