-- Migration 23: publish the seeded Medoria Health taxonomy.
--
-- Only categories introduced by migrations 20-22 are activated. Categories
-- created later by operators are not touched and remain under panel control.
begin;

with seeded(slug) as (
  values
    ('infection-prevention'),
    ('injection-infusion'),
    ('wound-dressings'),
    ('diagnostics-monitoring'),
    ('laboratory-testing'),
    ('surgery-procedures'),
    ('respiratory-anesthesia'),
    ('emergency-resuscitation'),
    ('nursing-patient-care'),
    ('urology-ostomy-continence'),
    ('orthopedics-rehabilitation'),
    ('medical-equipment-furniture'),
    ('maternal-pediatric-care'),
    ('medical-apparel-textiles'),
    ('gloves'),
    ('masks'),
    ('protective-apparel'),
    ('disinfection-antisepsis'),
    ('sterilization-waste'),
    ('syringes-needles'),
    ('vascular-access'),
    ('infusion-transfusion'),
    ('injection-infusion-accessories'),
    ('wound'),
    ('gauze-swabs'),
    ('bandages-tapes'),
    ('advanced-dressings'),
    ('burn-wound-cleansing'),
    ('diagnostics'),
    ('vital-signs-monitoring'),
    ('glucose-monitoring'),
    ('cardiology-monitoring'),
    ('examination-instruments'),
    ('imaging-consumables'),
    ('lab'),
    ('blood-collection'),
    ('specimen-collection'),
    ('rapid-testing'),
    ('laboratory-equipment-consumables'),
    ('instruments'),
    ('blades-sutures-closure'),
    ('procedure-packs-drapes'),
    ('suction-drainage'),
    ('operating-room-accessories'),
    ('oxygen-therapy'),
    ('nebulization'),
    ('airway-intubation'),
    ('breathing-circuits-filters'),
    ('resuscitation-suction'),
    ('anesthesia-supplies'),
    ('first-aid'),
    ('resuscitation'),
    ('immobilization'),
    ('transport-ambulance'),
    ('nursing-consumables'),
    ('patient-hygiene'),
    ('bed-protection-linen'),
    ('pressure-care'),
    ('enteral-feeding'),
    ('urinary-catheters'),
    ('urine-drainage'),
    ('ostomy-care'),
    ('continence-care'),
    ('supports-braces'),
    ('casting-splinting'),
    ('compression-therapy'),
    ('mobility-aids'),
    ('rehabilitation-patient-handling'),
    ('hospital-clinic-furniture'),
    ('patient-monitoring-equipment'),
    ('infusion-suction-equipment'),
    ('sterilization-equipment'),
    ('cold-chain'),
    ('clinic-diagnostic-equipment'),
    ('gynecology-obstetrics'),
    ('maternity-neonatal-care'),
    ('pediatric-care'),
    ('breastfeeding-infant-feeding'),
    ('clinical-apparel'),
    ('patient-apparel'),
    ('disposable-apparel'),
    ('medical-textiles')
)
update public.categories as category
set is_active = true
from seeded
where category.slug = seeded.slug;

commit;
