-- Migration 24: detailed clinical and procedure category leaves
-- Adds detailed level-3 Health product categories. All seeded leaves start active
-- and remain fully manageable from the Health operator category tree.
begin;

with leaf_data(slug, parent_slug, name_fa, name_en, icon, sort_order) as (
  values
    ('exam-gloves', 'gloves', 'دستکش معاینه', 'Examination Gloves', 'package', 10),
    ('surgical-gloves', 'gloves', 'دستکش جراحی', 'Surgical Gloves', 'package', 20),
    ('sterile-procedure-gloves', 'gloves', 'دستکش استریل پروسیجر', 'Sterile Procedure Gloves', 'package', 30),
    ('chemotherapy-gloves', 'gloves', 'دستکش مقاوم شیمی‌درمانی', 'Chemotherapy Gloves', 'package', 40),
    ('surgical-masks', 'masks', 'ماسک جراحی', 'Surgical Masks', 'package', 10),
    ('medical-face-masks', 'masks', 'ماسک پزشکی سه‌لایه', 'Medical Face Masks', 'package', 20),
    ('n95-ffp-respirators', 'masks', 'ماسک تنفسی N95 و FFP', 'N95 & FFP Respirators', 'package', 30),
    ('pediatric-masks', 'masks', 'ماسک اطفال', 'Pediatric Masks', 'package', 40),
    ('face-shields', 'masks', 'شیلد محافظ صورت', 'Face Shields', 'package', 50),
    ('isolation-gowns', 'protective-apparel', 'گان ایزوله', 'Isolation Gowns', 'package', 10),
    ('surgical-gowns', 'protective-apparel', 'گان جراحی', 'Surgical Gowns', 'package', 20),
    ('protective-coveralls', 'protective-apparel', 'لباس یکسره حفاظتی', 'Protective Coveralls', 'package', 30),
    ('medical-aprons', 'protective-apparel', 'پیش‌بند پزشکی', 'Medical Aprons', 'package', 40),
    ('caps-shoe-covers', 'protective-apparel', 'کلاه و کاور کفش', 'Caps & Shoe Covers', 'package', 50),
    ('eye-face-protection', 'protective-apparel', 'محافظ چشم و صورت', 'Eye & Face Protection', 'package', 60),
    ('hand-antiseptics', 'disinfection-antisepsis', 'ضدعفونی‌کننده دست', 'Hand Antiseptics', 'package', 10),
    ('surface-disinfectants', 'disinfection-antisepsis', 'ضدعفونی‌کننده سطوح', 'Surface Disinfectants', 'package', 20),
    ('instrument-disinfectants', 'disinfection-antisepsis', 'ضدعفونی‌کننده ابزار', 'Instrument Disinfectants', 'package', 30),
    ('skin-preparation', 'disinfection-antisepsis', 'محلول و پد آماده‌سازی پوست', 'Skin Preparation', 'package', 40),
    ('disinfectant-wipes', 'disinfection-antisepsis', 'دستمال ضدعفونی', 'Disinfectant Wipes', 'package', 50),
    ('sterilization-pouches-rolls', 'sterilization-waste', 'پاکت و رول استریل', 'Sterilization Pouches & Rolls', 'package', 10),
    ('sterilization-indicators', 'sterilization-waste', 'اندیکاتور استریلیزاسیون', 'Sterilization Indicators', 'package', 20),
    ('sharps-containers', 'sterilization-waste', 'ظروف اجسام تیز', 'Sharps Containers', 'package', 30),
    ('medical-waste-bags', 'sterilization-waste', 'کیسه پسماند پزشکی', 'Medical Waste Bags', 'package', 40),
    ('instrument-cleaning-brushes', 'sterilization-waste', 'برس شست‌وشوی ابزار', 'Instrument Cleaning Brushes', 'package', 50),
    ('disposable-syringes', 'syringes-needles', 'سرنگ یک‌بارمصرف', 'Disposable Syringes', 'package', 10),
    ('hypodermic-needles', 'syringes-needles', 'سرسوزن تزریق', 'Hypodermic Needles', 'package', 20),
    ('insulin-syringes', 'syringes-needles', 'سرنگ انسولین', 'Insulin Syringes', 'package', 30),
    ('safety-needles', 'syringes-needles', 'سرسوزن ایمن', 'Safety Needles', 'package', 40),
    ('prefilled-flush-syringes', 'syringes-needles', 'سرنگ شست‌وشوی آماده', 'Prefilled Flush Syringes', 'package', 50),
    ('iv-cannulas', 'vascular-access', 'آنژیوکت و کانول وریدی', 'IV Cannulas', 'package', 10),
    ('scalp-vein-sets', 'vascular-access', 'اسکالپ‌وین', 'Scalp Vein Sets', 'package', 20),
    ('central-venous-catheters', 'vascular-access', 'کاتتر ورید مرکزی', 'Central Venous Catheters', 'package', 30),
    ('picc-midline-catheters', 'vascular-access', 'کاتتر PICC و Midline', 'PICC & Midline Catheters', 'package', 40),
    ('catheter-securement', 'vascular-access', 'فیکس‌کننده کاتتر', 'Catheter Securement', 'package', 50),
    ('iv-infusion-sets', 'infusion-transfusion', 'ست سرم', 'IV Infusion Sets', 'package', 10),
    ('blood-transfusion-sets', 'infusion-transfusion', 'ست انتقال خون', 'Blood Transfusion Sets', 'package', 20),
    ('burette-microdrip-sets', 'infusion-transfusion', 'میکروست و بورت', 'Burette & Microdrip Sets', 'package', 30),
    ('gravity-feeding-sets', 'infusion-transfusion', 'ست انفوزیون ثقلی', 'Gravity Infusion Sets', 'package', 40),
    ('infusion-pump-sets', 'infusion-transfusion', 'ست پمپ انفوزیون', 'Infusion Pump Sets', 'package', 50),
    ('three-way-stopcocks', 'injection-infusion-accessories', 'سه‌راهی تزریق', 'Three-Way Stopcocks', 'package', 10),
    ('extension-lines', 'injection-infusion-accessories', 'اکستنشن تیوب', 'Extension Lines', 'package', 20),
    ('needle-free-connectors', 'injection-infusion-accessories', 'کانکتور بدون سوزن', 'Needle-Free Connectors', 'package', 30),
    ('injection-ports-caps', 'injection-infusion-accessories', 'پورت و درپوش تزریق', 'Injection Ports & Caps', 'package', 40),
    ('tourniquets', 'injection-infusion-accessories', 'تورنیکه و شریان‌بند', 'Tourniquets', 'package', 50),
    ('adhesive-wound-dressings', 'wound', 'پانسمان چسب‌دار', 'Adhesive Wound Dressings', 'package', 10),
    ('non-adherent-dressings', 'wound', 'پانسمان غیرچسبنده', 'Non-Adherent Dressings', 'package', 20),
    ('island-dressings', 'wound', 'پانسمان جزیره‌ای', 'Island Dressings', 'package', 30),
    ('wound-closure-strips', 'wound', 'نوار بستن زخم', 'Wound Closure Strips', 'package', 40),
    ('post-operative-dressings', 'wound', 'پانسمان پس از جراحی', 'Post-Operative Dressings', 'package', 50),
    ('sterile-gauze', 'gauze-swabs', 'گاز استریل', 'Sterile Gauze', 'package', 10),
    ('nonsterile-gauze', 'gauze-swabs', 'گاز غیراستریل', 'Non-Sterile Gauze', 'package', 20),
    ('cotton-rolls-balls', 'gauze-swabs', 'پنبه رولی و توپی', 'Cotton Rolls & Balls', 'package', 30),
    ('medical-swabs', 'gauze-swabs', 'سواب پزشکی', 'Medical Swabs', 'package', 40),
    ('laparotomy-sponges', 'gauze-swabs', 'گاز و اسپانج لاپاراتومی', 'Laparotomy Sponges', 'package', 50),
    ('elastic-bandages', 'bandages-tapes', 'باند کشی', 'Elastic Bandages', 'package', 10),
    ('cohesive-bandages', 'bandages-tapes', 'باند خودچسب', 'Cohesive Bandages', 'package', 20),
    ('crepe-bandages', 'bandages-tapes', 'باند کرپ', 'Crepe Bandages', 'package', 30),
    ('medical-adhesive-tapes', 'bandages-tapes', 'چسب و نوار پزشکی', 'Medical Adhesive Tapes', 'package', 40),
    ('tubular-bandages', 'bandages-tapes', 'باند توبولار', 'Tubular Bandages', 'package', 50),
    ('foam-dressings', 'advanced-dressings', 'پانسمان فوم', 'Foam Dressings', 'package', 10),
    ('hydrocolloid-dressings', 'advanced-dressings', 'پانسمان هیدروکلوئید', 'Hydrocolloid Dressings', 'package', 20),
    ('alginate-hydrofiber-dressings', 'advanced-dressings', 'پانسمان آلژینات و هیدروفایبر', 'Alginate & Hydrofiber Dressings', 'package', 30),
    ('antimicrobial-silver-dressings', 'advanced-dressings', 'پانسمان نقره و آنتی‌میکروبیال', 'Antimicrobial & Silver Dressings', 'package', 40),
    ('transparent-film-dressings', 'advanced-dressings', 'پانسمان فیلم شفاف', 'Transparent Film Dressings', 'package', 50),
    ('collagen-dressings', 'advanced-dressings', 'پانسمان کلاژن', 'Collagen Dressings', 'package', 60),
    ('burn-dressings', 'burn-wound-cleansing', 'پانسمان سوختگی', 'Burn Dressings', 'package', 10),
    ('wound-irrigation', 'burn-wound-cleansing', 'محلول و تجهیزات شست‌وشوی زخم', 'Wound Irrigation', 'package', 20),
    ('wound-cleansers', 'burn-wound-cleansing', 'پاک‌کننده زخم', 'Wound Cleansers', 'package', 30),
    ('debridement-products', 'burn-wound-cleansing', 'محصولات دبریدمان', 'Debridement Products', 'package', 40),
    ('skin-barrier-products', 'burn-wound-cleansing', 'محافظ پوست اطراف زخم', 'Skin Barrier Products', 'package', 50),
    ('blood-pressure-monitors', 'diagnostics', 'فشارسنج', 'Blood Pressure Monitors', 'package', 10),
    ('thermometers', 'diagnostics', 'تب‌سنج', 'Thermometers', 'package', 20),
    ('pulse-oximeters', 'diagnostics', 'پالس‌اکسی‌متر', 'Pulse Oximeters', 'package', 30),
    ('stethoscopes', 'diagnostics', 'گوشی پزشکی', 'Stethoscopes', 'package', 40),
    ('diagnostic-sets', 'diagnostics', 'ست تشخیصی', 'Diagnostic Sets', 'package', 50),
    ('multiparameter-monitors', 'vital-signs-monitoring', 'مانیتور چندپارامتری', 'Multiparameter Monitors', 'package', 10),
    ('blood-pressure-cuffs', 'vital-signs-monitoring', 'کاف فشار خون', 'Blood Pressure Cuffs', 'package', 20),
    ('spo2-sensors', 'vital-signs-monitoring', 'سنسور پالس‌اکسی‌متر', 'SpO2 Sensors', 'package', 30),
    ('temperature-probes', 'vital-signs-monitoring', 'پروب دما', 'Temperature Probes', 'package', 40),
    ('monitoring-cables-leads', 'vital-signs-monitoring', 'کابل و لید مانیتورینگ', 'Monitoring Cables & Leads', 'package', 50),
    ('glucometers', 'glucose-monitoring', 'دستگاه قند خون', 'Glucometers', 'package', 10),
    ('glucose-test-strips', 'glucose-monitoring', 'نوار تست قند خون', 'Glucose Test Strips', 'package', 20),
    ('lancing-devices-lancets', 'glucose-monitoring', 'لانست و قلم لنست', 'Lancing Devices & Lancets', 'package', 30),
    ('glucose-control-solutions', 'glucose-monitoring', 'محلول کنترل قند خون', 'Glucose Control Solutions', 'package', 40),
    ('ketone-testing', 'glucose-monitoring', 'تست کتون', 'Ketone Testing', 'package', 50),
    ('ecg-machines', 'cardiology-monitoring', 'دستگاه ECG', 'ECG Machines', 'package', 10),
    ('ecg-electrodes', 'cardiology-monitoring', 'الکترود ECG', 'ECG Electrodes', 'package', 20),
    ('ecg-paper', 'cardiology-monitoring', 'کاغذ ECG', 'ECG Paper', 'package', 30),
    ('holter-accessories', 'cardiology-monitoring', 'لوازم هولتر', 'Holter Accessories', 'package', 40),
    ('cardiac-monitoring-cables', 'cardiology-monitoring', 'کابل مانیتورینگ قلب', 'Cardiac Monitoring Cables', 'package', 50),
    ('otoscopes', 'examination-instruments', 'اتوسکوپ', 'Otoscopes', 'package', 10),
    ('ophthalmoscopes', 'examination-instruments', 'افتالموسکوپ', 'Ophthalmoscopes', 'package', 20),
    ('reflex-hammers', 'examination-instruments', 'چکش رفلکس', 'Reflex Hammers', 'package', 30),
    ('examination-lights', 'examination-instruments', 'چراغ معاینه', 'Examination Lights', 'package', 40),
    ('medical-scales-height-rods', 'examination-instruments', 'ترازو و قدسنج پزشکی', 'Medical Scales & Height Rods', 'package', 50),
    ('tuning-forks', 'examination-instruments', 'دیاپازون پزشکی', 'Medical Tuning Forks', 'package', 60),
    ('ultrasound-gel', 'imaging-consumables', 'ژل سونوگرافی', 'Ultrasound Gel', 'package', 10),
    ('ultrasound-probe-covers', 'imaging-consumables', 'کاور پروب سونوگرافی', 'Ultrasound Probe Covers', 'package', 20),
    ('medical-printer-paper', 'imaging-consumables', 'کاغذ پرینتر پزشکی', 'Medical Printer Paper', 'package', 30),
    ('radiology-markers', 'imaging-consumables', 'مارکر رادیولوژی', 'Radiology Markers', 'package', 40),
    ('biopsy-guides-covers', 'imaging-consumables', 'گاید و کاور بیوپسی', 'Biopsy Guides & Covers', 'package', 50),
    ('test-tubes-racks', 'lab', 'لوله آزمایش و رک', 'Test Tubes & Racks', 'package', 10),
    ('beakers-cylinders', 'lab', 'بشر و استوانه مدرج', 'Beakers & Graduated Cylinders', 'package', 20),
    ('reagent-bottles', 'lab', 'بطری و ظروف معرف', 'Reagent Bottles', 'package', 30),
    ('laboratory-trays-containers', 'lab', 'سینی و ظروف آزمایشگاهی', 'Laboratory Trays & Containers', 'package', 40),
    ('laboratory-labels', 'lab', 'لیبل و برچسب آزمایشگاهی', 'Laboratory Labels', 'package', 50),
    ('vacuum-blood-tubes', 'blood-collection', 'لوله خون‌گیری وکیوم', 'Vacuum Blood Collection Tubes', 'package', 10),
    ('blood-tube-holders', 'blood-collection', 'هولدر و آداپتور خون‌گیری', 'Blood Tube Holders & Adapters', 'package', 20),
    ('butterfly-blood-collection', 'blood-collection', 'سوزن پروانه‌ای خون‌گیری', 'Butterfly Blood Collection Sets', 'package', 30),
    ('blood-collection-needles', 'blood-collection', 'سرسوزن خون‌گیری', 'Blood Collection Needles', 'package', 40),
    ('capillary-collection', 'blood-collection', 'تجهیزات خون‌گیری مویرگی', 'Capillary Blood Collection', 'package', 50),
    ('urine-specimen-cups', 'specimen-collection', 'ظرف نمونه ادرار', 'Urine Specimen Cups', 'package', 10),
    ('stool-specimen-containers', 'specimen-collection', 'ظرف نمونه مدفوع', 'Stool Specimen Containers', 'package', 20),
    ('transport-swabs-media', 'specimen-collection', 'سواب و محیط انتقال نمونه', 'Transport Swabs & Media', 'package', 30),
    ('pathology-containers', 'specimen-collection', 'ظروف پاتولوژی', 'Pathology Containers', 'package', 40),
    ('specimen-transport-bags', 'specimen-collection', 'کیسه حمل نمونه', 'Specimen Transport Bags', 'package', 50),
    ('pregnancy-fertility-tests', 'rapid-testing', 'تست بارداری و باروری', 'Pregnancy & Fertility Tests', 'package', 10),
    ('infectious-disease-rapid-tests', 'rapid-testing', 'تست سریع بیماری‌های عفونی', 'Infectious Disease Rapid Tests', 'package', 20),
    ('cardiac-marker-tests', 'rapid-testing', 'تست مارکر قلبی', 'Cardiac Marker Tests', 'package', 30),
    ('urinalysis-strips', 'rapid-testing', 'نوار آزمایش ادرار', 'Urinalysis Strips', 'package', 40),
    ('point-of-care-analyzers', 'rapid-testing', 'آنالایزر Point-of-Care', 'Point-of-Care Analyzers', 'package', 50),
    ('centrifuges', 'laboratory-equipment-consumables', 'سانتریفیوژ', 'Centrifuges', 'package', 10),
    ('microscopes', 'laboratory-equipment-consumables', 'میکروسکوپ', 'Microscopes', 'package', 20),
    ('pipettes-tips', 'laboratory-equipment-consumables', 'پیپت، سمپلر و سرسمپلر', 'Pipettes & Tips', 'package', 30),
    ('laboratory-analyzers', 'laboratory-equipment-consumables', 'آنالایزر آزمایشگاهی', 'Laboratory Analyzers', 'package', 40),
    ('incubators-water-baths', 'laboratory-equipment-consumables', 'انکوباتور و بن‌ماری', 'Incubators & Water Baths', 'package', 50),
    ('laboratory-filters', 'laboratory-equipment-consumables', 'فیلترهای آزمایشگاهی', 'Laboratory Filters', 'package', 60),
    ('general-surgical-instruments', 'instruments', 'ابزار جراحی عمومی', 'General Surgical Instruments', 'package', 10),
    ('minor-procedure-instruments', 'instruments', 'ابزار جراحی کوچک و پروسیجر', 'Minor Procedure Instruments', 'package', 20),
    ('dressing-instruments', 'instruments', 'ابزار پانسمان', 'Dressing Instruments', 'package', 30),
    ('gynecology-instruments', 'instruments', 'ابزار زنان و زایمان', 'Gynecology Instruments', 'package', 40),
    ('ent-instruments', 'instruments', 'ابزار گوش، حلق و بینی', 'ENT Instruments', 'package', 50),
    ('scalpel-blades-handles', 'blades-sutures-closure', 'تیغ و دسته بیستوری', 'Scalpel Blades & Handles', 'package', 10),
    ('surgical-sutures', 'blades-sutures-closure', 'نخ بخیه جراحی', 'Surgical Sutures', 'package', 20),
    ('skin-staplers-removers', 'blades-sutures-closure', 'استپلر و ریموور پوستی', 'Skin Staplers & Removers', 'package', 30),
    ('ligation-clips', 'blades-sutures-closure', 'کلیپس و هموکلیپ', 'Ligation Clips', 'package', 40),
    ('wound-closure-adhesives', 'blades-sutures-closure', 'چسب بستن زخم', 'Wound Closure Adhesives', 'package', 50),
    ('dressing-packs', 'procedure-packs-drapes', 'پک پانسمان', 'Dressing Packs', 'package', 10),
    ('catheterization-packs', 'procedure-packs-drapes', 'پک سوندگذاری', 'Catheterization Packs', 'package', 20),
    ('minor-surgery-packs', 'procedure-packs-drapes', 'پک جراحی کوچک', 'Minor Surgery Packs', 'package', 30),
    ('sterile-surgical-drapes', 'procedure-packs-drapes', 'شان و پوشش استریل', 'Sterile Surgical Drapes', 'package', 40),
    ('delivery-packs', 'procedure-packs-drapes', 'پک زایمان', 'Delivery Packs', 'package', 50),
    ('suction-tubing', 'suction-drainage', 'لوله ساکشن', 'Suction Tubing', 'package', 10),
    ('suction-catheters', 'suction-drainage', 'کاتتر ساکشن', 'Suction Catheters', 'package', 20),
    ('surgical-drains', 'suction-drainage', 'درن جراحی', 'Surgical Drains', 'package', 30),
    ('closed-wound-drainage', 'suction-drainage', 'سیستم درناژ بسته زخم', 'Closed Wound Drainage', 'package', 40),
    ('drainage-bags-bottles', 'suction-drainage', 'کیسه و بطری درناژ', 'Drainage Bags & Bottles', 'package', 50),
    ('electrosurgery-accessories', 'operating-room-accessories', 'لوازم الکتروسرجری', 'Electrosurgery Accessories', 'package', 10),
    ('instrument-trays-cases', 'operating-room-accessories', 'سینی و جعبه ابزار جراحی', 'Instrument Trays & Cases', 'package', 20),
    ('surgical-sponges-patties', 'operating-room-accessories', 'اسفنج و پتی جراحی', 'Surgical Sponges & Patties', 'package', 30),
    ('or-table-accessories', 'operating-room-accessories', 'لوازم تخت اتاق عمل', 'Operating Table Accessories', 'package', 40),
    ('surgical-markers-rulers', 'operating-room-accessories', 'مارکر و خط‌کش جراحی', 'Surgical Markers & Rulers', 'package', 50)
)
insert into public.categories (
  slug, name_fa, name_en, icon,
  sort_order, is_active, is_featured, parent_id, level
)
select d.slug, d.name_fa, d.name_en, d.icon,
       d.sort_order, true, false, p.id, 3
from leaf_data d
join public.categories p on p.slug = d.parent_slug and p.level = 2
on conflict (slug) do update set
  name_fa = excluded.name_fa,
  name_en = excluded.name_en,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true,
  parent_id = excluded.parent_id,
  level = 3;

commit;
