-- Migration 25: detailed respiratory, emergency, nursing and continence category leaves
-- Adds detailed level-3 Health product categories. All seeded leaves start active
-- and remain fully manageable from the Health operator category tree.
begin;

with leaf_data(slug, parent_slug, name_fa, name_en, icon, sort_order) as (
  values
    ('oxygen-masks', 'oxygen-therapy', 'ماسک اکسیژن', 'Oxygen Masks', 'package', 10),
    ('nasal-cannulas', 'oxygen-therapy', 'کانولای بینی', 'Nasal Cannulas', 'package', 20),
    ('oxygen-tubing', 'oxygen-therapy', 'لوله اکسیژن', 'Oxygen Tubing', 'package', 30),
    ('humidifier-bottles', 'oxygen-therapy', 'بطری مرطوب‌کننده اکسیژن', 'Oxygen Humidifier Bottles', 'package', 40),
    ('oxygen-regulators-flowmeters', 'oxygen-therapy', 'رگلاتور و فلومتر اکسیژن', 'Oxygen Regulators & Flowmeters', 'package', 50),
    ('nebulizer-devices', 'nebulization', 'دستگاه نبولایزر', 'Nebulizer Devices', 'package', 10),
    ('nebulizer-kits-masks', 'nebulization', 'ست و ماسک نبولایزر', 'Nebulizer Kits & Masks', 'package', 20),
    ('nebulizer-medication-cups', 'nebulization', 'محفظه داروی نبولایزر', 'Nebulizer Medication Cups', 'package', 30),
    ('pediatric-nebulizer-accessories', 'nebulization', 'لوازم نبولایزر اطفال', 'Pediatric Nebulizer Accessories', 'package', 40),
    ('endotracheal-tubes', 'airway-intubation', 'لوله تراشه', 'Endotracheal Tubes', 'package', 10),
    ('laryngeal-masks', 'airway-intubation', 'ماسک حنجره‌ای', 'Laryngeal Masks', 'package', 20),
    ('oropharyngeal-airways', 'airway-intubation', 'ایروی دهانی', 'Oropharyngeal Airways', 'package', 30),
    ('laryngoscopes', 'airway-intubation', 'لارنگوسکوپ و تیغه', 'Laryngoscopes & Blades', 'package', 40),
    ('stylets-bougies', 'airway-intubation', 'استایلت و بوژی', 'Stylets & Bougies', 'package', 50),
    ('breathing-circuits', 'breathing-circuits-filters', 'مدار تنفسی', 'Breathing Circuits', 'package', 10),
    ('hme-filters', 'breathing-circuits-filters', 'فیلتر HME', 'HME Filters', 'package', 20),
    ('bacterial-viral-filters', 'breathing-circuits-filters', 'فیلتر باکتریال و ویروسی', 'Bacterial & Viral Filters', 'package', 30),
    ('breathing-connectors-elbows', 'breathing-circuits-filters', 'کانکتور و زانویی تنفسی', 'Breathing Connectors & Elbows', 'package', 40),
    ('spirometry-filters-mouthpieces', 'breathing-circuits-filters', 'فیلتر و دهانی اسپیرومتری', 'Spirometry Filters & Mouthpieces', 'package', 50),
    ('bag-valve-masks', 'resuscitation-suction', 'آمبوبگ', 'Bag Valve Masks', 'package', 10),
    ('manual-suction-devices', 'resuscitation-suction', 'ساکشن دستی', 'Manual Suction Devices', 'package', 20),
    ('respiratory-suction-catheters', 'resuscitation-suction', 'کاتتر ساکشن تنفسی', 'Respiratory Suction Catheters', 'package', 30),
    ('cpr-pocket-masks', 'resuscitation-suction', 'ماسک جیبی CPR', 'CPR Pocket Masks', 'package', 40),
    ('resuscitation-accessories', 'resuscitation-suction', 'لوازم احیای تنفسی', 'Resuscitation Accessories', 'package', 50),
    ('anesthesia-masks', 'anesthesia-supplies', 'ماسک بیهوشی', 'Anesthesia Masks', 'package', 10),
    ('spinal-epidural-needles', 'anesthesia-supplies', 'سوزن اسپاینال و اپیدورال', 'Spinal & Epidural Needles', 'package', 20),
    ('capnography-lines', 'anesthesia-supplies', 'لاین نمونه‌گیری کاپنوگرافی', 'Capnography Sampling Lines', 'package', 30),
    ('anesthesia-breathing-bags', 'anesthesia-supplies', 'کیسه تنفسی بیهوشی', 'Anesthesia Breathing Bags', 'package', 40),
    ('bite-blocks-airway-accessories', 'anesthesia-supplies', 'بایت‌بلاک و لوازم راه هوایی', 'Bite Blocks & Airway Accessories', 'package', 50),
    ('first-aid-kits', 'first-aid', 'جعبه و کیف کمک‌های اولیه', 'First Aid Kits', 'package', 10),
    ('trauma-dressings', 'first-aid', 'پانسمان تروما', 'Trauma Dressings', 'package', 20),
    ('instant-hot-cold-packs', 'first-aid', 'پک گرم و سرد فوری', 'Instant Hot & Cold Packs', 'package', 30),
    ('eye-wash-products', 'first-aid', 'محصولات شست‌وشوی چشم', 'Eye Wash Products', 'package', 40),
    ('emergency-blankets', 'first-aid', 'پتو نجات', 'Emergency Blankets', 'package', 50),
    ('aed-pads-accessories', 'resuscitation', 'پد و لوازم AED', 'AED Pads & Accessories', 'package', 10),
    ('cpr-masks-shields', 'resuscitation', 'ماسک و شیلد CPR', 'CPR Masks & Shields', 'package', 20),
    ('resuscitation-boards', 'resuscitation', 'تخته احیا', 'Resuscitation Boards', 'package', 30),
    ('defibrillator-accessories', 'resuscitation', 'لوازم دفیبریلاتور', 'Defibrillator Accessories', 'package', 40),
    ('emergency-airway-kits', 'resuscitation', 'کیت راه هوایی اورژانس', 'Emergency Airway Kits', 'package', 50),
    ('cervical-collars', 'immobilization', 'گردنبند طبی اورژانس', 'Cervical Collars', 'package', 10),
    ('emergency-splints', 'immobilization', 'آتل اورژانس', 'Emergency Splints', 'package', 20),
    ('spinal-boards', 'immobilization', 'بک‌بورد ستون فقرات', 'Spinal Boards', 'package', 30),
    ('head-immobilizers', 'immobilization', 'ثابت‌کننده سر', 'Head Immobilizers', 'package', 40),
    ('vacuum-splints-mattresses', 'immobilization', 'آتل و تشک وکیوم', 'Vacuum Splints & Mattresses', 'package', 50),
    ('patient-stretchers', 'transport-ambulance', 'برانکارد', 'Patient Stretchers', 'package', 10),
    ('ambulance-bags-cases', 'transport-ambulance', 'کیف و کمد آمبولانس', 'Ambulance Bags & Cases', 'package', 20),
    ('transfer-sheets-boards', 'transport-ambulance', 'شیت و تخته انتقال بیمار', 'Transfer Sheets & Boards', 'package', 30),
    ('evacuation-chairs', 'transport-ambulance', 'صندلی تخلیه اضطراری', 'Evacuation Chairs', 'package', 40),
    ('ambulance-consumables', 'transport-ambulance', 'مصرفی‌های آمبولانس', 'Ambulance Consumables', 'package', 50),
    ('medicine-cups-spoons', 'nursing-consumables', 'لیوان و قاشق دارو', 'Medicine Cups & Spoons', 'package', 10),
    ('kidney-dishes-trays', 'nursing-consumables', 'رسیور و سینی پزشکی', 'Kidney Dishes & Trays', 'package', 20),
    ('tongue-depressors', 'nursing-consumables', 'آبسلانگ', 'Tongue Depressors', 'package', 30),
    ('bedpans-urinals', 'nursing-consumables', 'لگن و لوله ادرار بیمار', 'Bedpans & Urinals', 'package', 40),
    ('measuring-cups-containers', 'nursing-consumables', 'پیمانه و ظروف اندازه‌گیری', 'Measuring Cups & Containers', 'package', 50),
    ('bathing-wipes', 'patient-hygiene', 'دستمال حمام بیمار', 'Bathing Wipes', 'package', 10),
    ('oral-care-kits', 'patient-hygiene', 'کیت بهداشت دهان بیمار', 'Oral Care Kits', 'package', 20),
    ('shampoo-caps', 'patient-hygiene', 'کلاه شامپو بدون آب', 'Shampoo Caps', 'package', 30),
    ('skin-cleansers', 'patient-hygiene', 'پاک‌کننده پوست بیمار', 'Skin Cleansers', 'package', 40),
    ('barrier-creams', 'patient-hygiene', 'کرم محافظ پوست', 'Barrier Creams', 'package', 50),
    ('underpads', 'bed-protection-linen', 'زیرانداز بیمار', 'Underpads', 'package', 10),
    ('mattress-protectors', 'bed-protection-linen', 'محافظ تشک', 'Mattress Protectors', 'package', 20),
    ('disposable-bed-sheets', 'bed-protection-linen', 'ملحفه یک‌بارمصرف', 'Disposable Bed Sheets', 'package', 30),
    ('pillow-covers', 'bed-protection-linen', 'روبالشی بیمارستانی', 'Pillow Covers', 'package', 40),
    ('examination-table-rolls', 'bed-protection-linen', 'رول تخت معاینه', 'Examination Table Rolls', 'package', 50),
    ('pressure-relief-mattresses', 'pressure-care', 'تشک مواج و کاهنده فشار', 'Pressure Relief Mattresses', 'package', 10),
    ('pressure-relief-cushions', 'pressure-care', 'کوسن کاهنده فشار', 'Pressure Relief Cushions', 'package', 20),
    ('heel-elbow-protectors', 'pressure-care', 'محافظ پاشنه و آرنج', 'Heel & Elbow Protectors', 'package', 30),
    ('patient-repositioning-aids', 'pressure-care', 'لوازم تغییر وضعیت بیمار', 'Patient Repositioning Aids', 'package', 40),
    ('pressure-injury-dressings', 'pressure-care', 'پانسمان پیشگیری زخم فشاری', 'Pressure Injury Dressings', 'package', 50),
    ('feeding-tubes', 'enteral-feeding', 'لوله تغذیه', 'Feeding Tubes', 'package', 10),
    ('enteral-syringes', 'enteral-feeding', 'سرنگ تغذیه', 'Enteral Syringes', 'package', 20),
    ('feeding-bags-sets', 'enteral-feeding', 'کیسه و ست تغذیه', 'Feeding Bags & Sets', 'package', 30),
    ('enteral-pump-accessories', 'enteral-feeding', 'لوازم پمپ تغذیه', 'Enteral Pump Accessories', 'package', 40),
    ('nasogastric-tubes', 'enteral-feeding', 'سوند معده', 'Nasogastric Tubes', 'package', 50),
    ('foley-catheters', 'urinary-catheters', 'سوند فولی', 'Foley Catheters', 'package', 10),
    ('intermittent-nelaton-catheters', 'urinary-catheters', 'سوند نلاتون و متناوب', 'Intermittent & Nelaton Catheters', 'package', 20),
    ('suprapubic-catheters', 'urinary-catheters', 'سوند سوپراپوبیک', 'Suprapubic Catheters', 'package', 30),
    ('external-condom-catheters', 'urinary-catheters', 'کاندوم کاتتر', 'External Condom Catheters', 'package', 40),
    ('catheterization-kits', 'urinary-catheters', 'کیت سوندگذاری', 'Catheterization Kits', 'package', 50),
    ('urine-drainage-bags', 'urine-drainage', 'کیسه ادرار', 'Urine Drainage Bags', 'package', 10),
    ('leg-bags', 'urine-drainage', 'کیسه ادرار پایی', 'Leg Bags', 'package', 20),
    ('urine-meters', 'urine-drainage', 'یورین‌متر', 'Urine Meters', 'package', 30),
    ('catheter-valves', 'urine-drainage', 'شیر و والو سوند', 'Catheter Valves', 'package', 40),
    ('urine-drainage-bottles', 'urine-drainage', 'بطری جمع‌آوری ادرار', 'Urine Drainage Bottles', 'package', 50),
    ('colostomy-bags', 'ostomy-care', 'کیسه کلستومی', 'Colostomy Bags', 'package', 10),
    ('ileostomy-urostomy-bags', 'ostomy-care', 'کیسه ایلئوستومی و یوروستومی', 'Ileostomy & Urostomy Bags', 'package', 20),
    ('ostomy-skin-barriers', 'ostomy-care', 'چسب و محافظ پوست استومی', 'Ostomy Skin Barriers', 'package', 30),
    ('ostomy-pastes-rings', 'ostomy-care', 'خمیر و حلقه استومی', 'Ostomy Pastes & Rings', 'package', 40),
    ('ostomy-accessories', 'ostomy-care', 'لوازم جانبی استومی', 'Ostomy Accessories', 'package', 50),
    ('adult-diapers', 'continence-care', 'پوشک بزرگسال', 'Adult Diapers', 'package', 10),
    ('absorbent-pads', 'continence-care', 'پد بی‌اختیاری', 'Absorbent Pads', 'package', 20),
    ('protective-underwear', 'continence-care', 'شورت جاذب', 'Protective Underwear', 'package', 30),
    ('bed-chair-pads', 'continence-care', 'پد محافظ تخت و صندلی', 'Bed & Chair Pads', 'package', 40),
    ('continence-skincare', 'continence-care', 'مراقبت پوست بی‌اختیاری', 'Continence Skincare', 'package', 50)
)
insert into public.categories (
  slug, name_fa, name_en, icon,
  sort_order, is_active, is_featured, parent_id, level
)
select d.slug, d.name_fa, d.name_en, d.icon,
       d.sort_order, true, false, p.id, 3
from leaf_data d
join public.categories p on p.slug = d.parent_slug and p.level = 2
on conflict (slug) do update set
  name_fa = excluded.name_fa,
  name_en = excluded.name_en,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true,
  parent_id = excluded.parent_id,
  level = 3;

commit;
