-- Migration 26: detailed rehabilitation, equipment, maternal and textile category leaves
-- Adds detailed level-3 Health product categories. All seeded leaves start active
-- and remain fully manageable from the Health operator category tree.
begin;

with leaf_data(slug, parent_slug, name_fa, name_en, icon, sort_order) as (
  values
    ('knee-supports-braces', 'supports-braces', 'زانوبند و بریس زانو', 'Knee Supports & Braces', 'package', 10),
    ('ankle-foot-supports', 'supports-braces', 'ساپورت مچ و پا', 'Ankle & Foot Supports', 'package', 20),
    ('wrist-hand-supports', 'supports-braces', 'مچ‌بند و ساپورت دست', 'Wrist & Hand Supports', 'package', 30),
    ('back-abdominal-supports', 'supports-braces', 'کمربند و شکم‌بند طبی', 'Back & Abdominal Supports', 'package', 40),
    ('cervical-supports', 'supports-braces', 'گردنبند طبی', 'Cervical Supports', 'package', 50),
    ('shoulder-elbow-supports', 'supports-braces', 'ساپورت شانه و آرنج', 'Shoulder & Elbow Supports', 'package', 60),
    ('plaster-bandages', 'casting-splinting', 'باند گچی', 'Plaster Bandages', 'package', 10),
    ('fiberglass-casting-tape', 'casting-splinting', 'نوار فایبرگلاس', 'Fiberglass Casting Tape', 'package', 20),
    ('ready-made-splints', 'casting-splinting', 'آتل آماده', 'Ready-Made Splints', 'package', 30),
    ('cast-padding-stockinette', 'casting-splinting', 'پد و استاکینت گچ', 'Cast Padding & Stockinette', 'package', 40),
    ('cast-removal-accessories', 'casting-splinting', 'لوازم بازکردن گچ', 'Cast Removal Accessories', 'package', 50),
    ('compression-stockings', 'compression-therapy', 'جوراب فشاری', 'Compression Stockings', 'package', 10),
    ('compression-bandages', 'compression-therapy', 'باند فشاری', 'Compression Bandages', 'package', 20),
    ('intermittent-compression-sleeves', 'compression-therapy', 'کاف فشار متناوب', 'Intermittent Compression Sleeves', 'package', 30),
    ('lymphedema-garments', 'compression-therapy', 'پوشاک لنف‌ادم', 'Lymphedema Garments', 'package', 40),
    ('anti-embolism-stockings', 'compression-therapy', 'جوراب ضد آمبولی', 'Anti-Embolism Stockings', 'package', 50),
    ('walking-canes', 'mobility-aids', 'عصا', 'Walking Canes', 'package', 10),
    ('crutches', 'mobility-aids', 'عصای زیربغل و آرنجی', 'Crutches', 'package', 20),
    ('walkers-rollators', 'mobility-aids', 'واکر و رولیتر', 'Walkers & Rollators', 'package', 30),
    ('wheelchairs', 'mobility-aids', 'ویلچر', 'Wheelchairs', 'package', 40),
    ('commode-chairs', 'mobility-aids', 'صندلی توالت بیمار', 'Commode Chairs', 'package', 50),
    ('transfer-boards-belts', 'rehabilitation-patient-handling', 'تخته و کمربند انتقال', 'Transfer Boards & Belts', 'package', 10),
    ('patient-lifts-slings', 'rehabilitation-patient-handling', 'بالابر و اسلینگ بیمار', 'Patient Lifts & Slings', 'package', 20),
    ('therapy-exercise-products', 'rehabilitation-patient-handling', 'لوازم تمرین و فیزیوتراپی', 'Therapy & Exercise Products', 'package', 30),
    ('gait-training-aids', 'rehabilitation-patient-handling', 'لوازم تمرین راه‌رفتن', 'Gait Training Aids', 'package', 40),
    ('positioning-supports', 'rehabilitation-patient-handling', 'پوزیشنر و ساپورت وضعیت بدن', 'Positioning Supports', 'package', 50),
    ('hospital-beds', 'hospital-clinic-furniture', 'تخت بیمارستانی', 'Hospital Beds', 'package', 10),
    ('examination-tables', 'hospital-clinic-furniture', 'تخت معاینه', 'Examination Tables', 'package', 20),
    ('treatment-chairs', 'hospital-clinic-furniture', 'صندلی درمان و پروسیجر', 'Treatment & Procedure Chairs', 'package', 30),
    ('medical-trolleys', 'hospital-clinic-furniture', 'ترالی پزشکی', 'Medical Trolleys', 'package', 40),
    ('bedside-cabinets-tables', 'hospital-clinic-furniture', 'کمد و میز کنار تخت', 'Bedside Cabinets & Tables', 'package', 50),
    ('privacy-screens', 'hospital-clinic-furniture', 'پاراوان و جداکننده', 'Privacy Screens', 'package', 60),
    ('vital-signs-monitors', 'patient-monitoring-equipment', 'مانیتور علائم حیاتی', 'Vital Signs Monitors', 'package', 10),
    ('bedside-patient-monitors', 'patient-monitoring-equipment', 'مانیتور کنار تخت', 'Bedside Patient Monitors', 'package', 20),
    ('central-monitoring-systems', 'patient-monitoring-equipment', 'سیستم مانیتورینگ مرکزی', 'Central Monitoring Systems', 'package', 30),
    ('portable-ecg-devices', 'patient-monitoring-equipment', 'دستگاه ECG پرتابل', 'Portable ECG Devices', 'package', 40),
    ('monitoring-accessories', 'patient-monitoring-equipment', 'لوازم جانبی مانیتورینگ', 'Monitoring Accessories', 'package', 50),
    ('infusion-pumps', 'infusion-suction-equipment', 'پمپ سرم', 'Infusion Pumps', 'package', 10),
    ('syringe-pumps', 'infusion-suction-equipment', 'سرنگ پمپ', 'Syringe Pumps', 'package', 20),
    ('medical-suction-machines', 'infusion-suction-equipment', 'دستگاه ساکشن', 'Medical Suction Machines', 'package', 30),
    ('pump-docking-stations', 'infusion-suction-equipment', 'داک و پایه پمپ', 'Pump Docking Stations', 'package', 40),
    ('infusion-pump-accessories', 'infusion-suction-equipment', 'لوازم پمپ انفوزیون', 'Infusion Pump Accessories', 'package', 50),
    ('steam-autoclaves', 'sterilization-equipment', 'اتوکلاو بخار', 'Steam Autoclaves', 'package', 10),
    ('ultrasonic-cleaners', 'sterilization-equipment', 'شوینده اولتراسونیک', 'Ultrasonic Cleaners', 'package', 20),
    ('pouch-sealers', 'sterilization-equipment', 'دستگاه سیل پک استریل', 'Pouch Sealers', 'package', 30),
    ('sterilization-trays-containers', 'sterilization-equipment', 'سینی و کانتینر استریل', 'Sterilization Trays & Containers', 'package', 40),
    ('instrument-washers', 'sterilization-equipment', 'دستگاه شست‌وشوی ابزار', 'Instrument Washers', 'package', 50),
    ('medical-refrigerators', 'cold-chain', 'یخچال پزشکی', 'Medical Refrigerators', 'package', 10),
    ('vaccine-refrigerators', 'cold-chain', 'یخچال واکسن', 'Vaccine Refrigerators', 'package', 20),
    ('cold-boxes-vaccine-carriers', 'cold-chain', 'کول‌باکس و واکسن‌کریر', 'Cold Boxes & Vaccine Carriers', 'package', 30),
    ('ice-packs', 'cold-chain', 'آیس‌پک پزشکی', 'Medical Ice Packs', 'package', 40),
    ('temperature-data-loggers', 'cold-chain', 'دیتالاگر دما', 'Temperature Data Loggers', 'package', 50),
    ('cold-chain-monitors', 'cold-chain', 'اندیکاتور و مانیتور زنجیره سرد', 'Cold Chain Monitors', 'package', 60),
    ('medical-examination-lights', 'clinic-diagnostic-equipment', 'چراغ پزشکی و معاینه', 'Medical Examination Lights', 'package', 10),
    ('medical-scales', 'clinic-diagnostic-equipment', 'ترازو پزشکی', 'Medical Scales', 'package', 20),
    ('vascular-fetal-dopplers', 'clinic-diagnostic-equipment', 'داپلر عروقی و جنینی', 'Vascular & Fetal Dopplers', 'package', 30),
    ('spirometers', 'clinic-diagnostic-equipment', 'اسپیرومتر', 'Spirometers', 'package', 40),
    ('diagnostic-wall-systems', 'clinic-diagnostic-equipment', 'سیستم تشخیصی دیواری', 'Diagnostic Wall Systems', 'package', 50),
    ('audiometers', 'clinic-diagnostic-equipment', 'ادیومتر', 'Audiometers', 'package', 60),
    ('vaginal-speculums', 'gynecology-obstetrics', 'اسپکولوم واژینال', 'Vaginal Speculums', 'package', 10),
    ('cervical-sampling-products', 'gynecology-obstetrics', 'ابزار نمونه‌گیری دهانه رحم', 'Cervical Sampling Products', 'package', 20),
    ('iud-insertion-instruments', 'gynecology-obstetrics', 'ابزار گذاشتن IUD', 'IUD Insertion Instruments', 'package', 30),
    ('gynecology-examination-sets', 'gynecology-obstetrics', 'ست معاینه زنان', 'Gynecology Examination Sets', 'package', 40),
    ('amniotic-membrane-tools', 'gynecology-obstetrics', 'ابزار آمنیوتومی', 'Amniotomy Instruments', 'package', 50),
    ('delivery-kits', 'maternity-neonatal-care', 'کیت و ست زایمان', 'Delivery Kits', 'package', 10),
    ('neonatal-resuscitation', 'maternity-neonatal-care', 'تجهیزات احیای نوزاد', 'Neonatal Resuscitation', 'package', 20),
    ('umbilical-care', 'maternity-neonatal-care', 'مراقبت بند ناف', 'Umbilical Care', 'package', 30),
    ('infant-warmers-phototherapy', 'maternity-neonatal-care', 'وارمر و فتوتراپی نوزاد', 'Infant Warmers & Phototherapy', 'package', 40),
    ('neonatal-monitoring-accessories', 'maternity-neonatal-care', 'لوازم پایش نوزاد', 'Neonatal Monitoring Accessories', 'package', 50),
    ('pediatric-oxygen-products', 'pediatric-care', 'ماسک و کانولای اطفال', 'Pediatric Oxygen Products', 'package', 10),
    ('pediatric-catheters-tubes', 'pediatric-care', 'سوند و لوله اطفال', 'Pediatric Catheters & Tubes', 'package', 20),
    ('pediatric-monitoring', 'pediatric-care', 'تجهیزات پایش اطفال', 'Pediatric Monitoring', 'package', 30),
    ('infant-scales-measuring', 'pediatric-care', 'ترازو و اندازه‌گیری نوزاد', 'Infant Scales & Measuring', 'package', 40),
    ('pediatric-examination-supplies', 'pediatric-care', 'ملزومات معاینه اطفال', 'Pediatric Examination Supplies', 'package', 50),
    ('breast-pumps', 'breastfeeding-infant-feeding', 'شیردوش', 'Breast Pumps', 'package', 10),
    ('breast-milk-storage', 'breastfeeding-infant-feeding', 'ظروف نگهداری شیر مادر', 'Breast Milk Storage', 'package', 20),
    ('feeding-bottles-teats', 'breastfeeding-infant-feeding', 'شیشه شیر و سرشیشه', 'Feeding Bottles & Teats', 'package', 30),
    ('nipple-breast-care', 'breastfeeding-infant-feeding', 'مراقبت پستان و نوک سینه', 'Nipple & Breast Care', 'package', 40),
    ('infant-feeding-accessories', 'breastfeeding-infant-feeding', 'لوازم تغذیه نوزاد', 'Infant Feeding Accessories', 'package', 50),
    ('medical-scrubs', 'clinical-apparel', 'اسکراب پزشکی', 'Medical Scrubs', 'package', 10),
    ('lab-coats', 'clinical-apparel', 'روپوش آزمایشگاه و پزشکی', 'Lab Coats', 'package', 20),
    ('clinical-jackets', 'clinical-apparel', 'ژاکت و لباس کادر درمان', 'Clinical Jackets', 'package', 30),
    ('medical-footwear', 'clinical-apparel', 'کفش پزشکی', 'Medical Footwear', 'package', 40),
    ('reusable-clinical-caps', 'clinical-apparel', 'کلاه پارچه‌ای پزشکی', 'Reusable Clinical Caps', 'package', 50),
    ('patient-gowns', 'patient-apparel', 'لباس بیمار', 'Patient Gowns', 'package', 10),
    ('maternity-patient-gowns', 'patient-apparel', 'لباس بیمار بارداری و زایمان', 'Maternity Patient Gowns', 'package', 20),
    ('pediatric-patient-gowns', 'patient-apparel', 'لباس بیمار اطفال', 'Pediatric Patient Gowns', 'package', 30),
    ('patient-slippers', 'patient-apparel', 'دمپایی بیمار', 'Patient Slippers', 'package', 40),
    ('patient-robes', 'patient-apparel', 'روب و پوشش بیمار', 'Patient Robes', 'package', 50),
    ('disposable-isolation-gowns', 'disposable-apparel', 'گان ایزوله یک‌بارمصرف', 'Disposable Isolation Gowns', 'package', 10),
    ('disposable-aprons', 'disposable-apparel', 'پیش‌بند یک‌بارمصرف', 'Disposable Aprons', 'package', 20),
    ('disposable-caps', 'disposable-apparel', 'کلاه یک‌بارمصرف', 'Disposable Caps', 'package', 30),
    ('disposable-shoe-covers', 'disposable-apparel', 'کاور کفش یک‌بارمصرف', 'Disposable Shoe Covers', 'package', 40),
    ('disposable-sleeve-covers', 'disposable-apparel', 'کاور آستین یک‌بارمصرف', 'Disposable Sleeve Covers', 'package', 50),
    ('hospital-bed-sheets', 'medical-textiles', 'ملحفه بیمارستانی', 'Hospital Bed Sheets', 'package', 10),
    ('hospital-blankets', 'medical-textiles', 'پتو بیمارستانی', 'Hospital Blankets', 'package', 20),
    ('medical-towels', 'medical-textiles', 'حوله پزشکی و بیمارستانی', 'Medical Towels', 'package', 30),
    ('privacy-curtains', 'medical-textiles', 'پرده حریم خصوصی', 'Privacy Curtains', 'package', 40),
    ('reusable-surgical-drapes', 'medical-textiles', 'شان پارچه‌ای جراحی', 'Reusable Surgical Drapes', 'package', 50),
    ('mattress-pillow-covers', 'medical-textiles', 'روکش تشک و بالش', 'Mattress & Pillow Covers', 'package', 60)
)
insert into public.categories (
  slug, name_fa, name_en, icon,
  sort_order, is_active, is_featured, parent_id, level
)
select d.slug, d.name_fa, d.name_en, d.icon,
       d.sort_order, true, false, p.id, 3
from leaf_data d
join public.categories p on p.slug = d.parent_slug and p.level = 2
on conflict (slug) do update set
  name_fa = excluded.name_fa,
  name_en = excluded.name_en,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true,
  parent_id = excluded.parent_id,
  level = 3;

commit;
