// lib/beauty/categoryImages.js
// GENERATED by scripts/build_category_tiles.mjs — do not edit by hand.
// Maps a category slug to its tile in public/beauty/categories/.
// An uploaded beauty_categories.image_url always takes precedence over this.
export const CATEGORY_IMG = {
  "air-freshener": "/beauty/categories/air-freshener.webp",
  "body-care": "/beauty/categories/body-care.webp",
  "face-care": "/beauty/categories/face-care.webp",
  "perfume-cologne": "/beauty/categories/perfume-cologne.webp",
  "perfume-gift-set": "/beauty/categories/perfume-gift-set.webp",
  "perfume-kids": "/beauty/categories/perfume-kids.webp",
  "perfume-men": "/beauty/categories/perfume-men.webp",
  "perfume-unisex": "/beauty/categories/perfume-unisex.webp",
  "perfume-women": "/beauty/categories/perfume-women.webp",
};
