// lib/beauty/categoryImages.js
// GENERATED by scripts/build_category_tiles.mjs — do not edit by hand.
// Maps a category slug to its tile in public/beauty/categories/.
// An uploaded beauty_categories.image_url always takes precedence over this.
export const CATEGORY_IMG = {
  "air-freshener": "/beauty/categories/air-freshener.webp",
  "baby-care": "/beauty/categories/baby-care.webp",
  "body-care": "/beauty/categories/body-care.webp",
  "body-mist": "/beauty/categories/body-mist.webp",
  "body-splash": "/beauty/categories/body-splash.webp",
  "brow-makeup": "/beauty/categories/brow-makeup.webp",
  "eye-makeup": "/beauty/categories/eye-makeup.webp",
  "face-care": "/beauty/categories/face-care.webp",
  "face-makeup": "/beauty/categories/face-makeup.webp",
  "fragrances": "/beauty/categories/fragrances.webp",
  "hygiene-sets": "/beauty/categories/hygiene-sets.webp",
  "intimate": "/beauty/categories/intimate.webp",
  "lip-makeup": "/beauty/categories/lip-makeup.webp",
  "mens-care": "/beauty/categories/mens-care.webp",
  "oral-care": "/beauty/categories/oral-care.webp",
  "perfume-cologne": "/beauty/categories/perfume-cologne.webp",
  "perfume-gift-set": "/beauty/categories/perfume-gift-set.webp",
  "perfume-kids": "/beauty/categories/perfume-kids.webp",
  "perfume-men": "/beauty/categories/perfume-men.webp",
  "perfume-spray": "/beauty/categories/perfume-spray.webp",
  "perfume-unisex": "/beauty/categories/perfume-unisex.webp",
  "perfume-women": "/beauty/categories/perfume-women.webp",
  "shaving": "/beauty/categories/shaving.webp",
  "skin-hair-supplement": "/beauty/categories/skin-hair-supplement.webp",
};
