// lib/beauty/categoryImages.js
// GENERATED by scripts/build_category_tiles.mjs — do not edit by hand.
// Maps a category slug to its tile in public/beauty/categories/.
// An uploaded beauty_categories.image_url always takes precedence over this.
export const CATEGORY_IMG = {
  "face-care": "/beauty/categories/face-care.webp",
  "body-care": "/beauty/categories/body-care.webp",
};
