-- migrations/12_parts/02_personal-care.sql
-- Part 3 of 8 — run AFTER 00_schema.sql, in any order relative to
-- the other department files (this one only references its own rows).
-- GENERATED by scripts/split_beauty_tree_sql.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here.

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('personal-care', NULL, 1, 'personal-care', 'Маҳсулоти беҳдоштӣ', 'Гигиена и уход', 'Personal Care', 'بهداشتی', 'droplet', 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-care', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Нигоҳубини рӯй', 'Уход за лицом', 'Face Care', 'مراقبت از صورت', 'sparkles', 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('day-cream', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Кремии рӯзона', 'Дневной крем', 'Day Cream', 'کرم روز', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('night-cream', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Кремии шабона', 'Ночной крем', 'Night Cream', 'کرم شب', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eye-cream', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Кремии атрофи чашм', 'Крем для век', 'Eye Cream', 'کرم دور چشم', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('exfoliator', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Лоядоракунанда', 'Эксфолиант', 'Exfoliator', 'لایه‌بردار', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('anti-aging', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Зидди пирӣ ва афтидагӣ', 'Антивозрастной уход', 'Anti-Aging & Firming', 'ضد چروک و ضد افتادگی', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brightening', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Зидди доғ ва равшанкунанда', 'Против пигментации', 'Anti-Blemish & Brightening', 'ضد لک و روشن‌کننده', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mask-scrub', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Ниқоб ва скраб', 'Маски и скрабы', 'Masks & Scrubs', 'ماسک و اسکراب', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('acne-pore', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Табобати ҷӯш ва манфаз', 'Против акне и пор', 'Acne & Pore Care', 'درمان جوش و منافذ باز', NULL, 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('cleanser', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Тозакунанда ва шӯянда', 'Очищающие средства', 'Cleansers', 'پاک‌کننده و شوینده', NULL, 90, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-serum', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Серуми пӯст', 'Сыворотка для лица', 'Facial Serum', 'سرم پوست', NULL, 100, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('moisturizer', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Намноккунанда', 'Увлажняющее средство', 'Moisturizer', 'مرطوب‌کننده', NULL, 110, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('facial-mist', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Спрейи об', 'Термальная вода', 'Facial Mist', 'اسپری آب', NULL, 120, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('sunscreen', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Зидди офтоб', 'Солнцезащитный крем', 'Sunscreen', 'ضد آفتاب', NULL, 130, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('tanning', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Маҳсулоти офтобӣ ва автозагар', 'Загар и автозагар', 'Sun & Self-Tan', 'محصولات آفتاب و اتو برنز', NULL, 140, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lash-brow-care', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Нигоҳубини мижа ва абрӯ', 'Уход за ресницами и бровями', 'Lash & Brow Care', 'مراقبت از مژه و ابرو', NULL, 150, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-care', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Нигоҳубини лаб', 'Уход за губами', 'Lip Care', 'مراقبت از لب', NULL, 160, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-scrub', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Скраби рӯй', 'Скраб для лица', 'Face Scrub', 'اسکراب صورت', NULL, 170, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-mask', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Ниқоби рӯй', 'Маска для лица', 'Face Mask', 'ماسک صورت', NULL, 180, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('nose-strips', (SELECT id FROM beauty_categories WHERE slug='face-care'), 3, 'personal-care', 'Тасмаи бинӣ', 'Полоски для носа', 'Nose Strips', 'چسب بینی', NULL, 190, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('body-care', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Нигоҳубини бадан', 'Уход за телом', 'Body Care', 'مراقبت از بدن', 'droplet', 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('womens-care', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Маҳсулоти занона', 'Женская гигиена', 'Women''s Care', 'محصولات بانوان', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('body-wash', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Шӯяндаи бадан', 'Гель для душа', 'Body Wash', 'شوینده بدن', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('body-lotion', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Лосиони бадан', 'Лосьон для тела', 'Body Lotion', 'لوسیون بدن', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('deodorant', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Дезодорант ва хушбӯйкунанда', 'Дезодорант', 'Deodorant', 'دئودورانت و خوشبوکننده', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('sanitizer', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Дезинфексиякунанда', 'Антисептик', 'Sanitizer', 'ضدعفونی‌کننده', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('body-oil', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Равғани бадан', 'Масло для тела', 'Body Oil', 'روغن بدن', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('pain-relief', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Зидди дард, сӯхтагӣ ва илтиҳоб', 'Против боли и воспаления', 'Pain & Burn Relief', 'ضد درد، سوختگی و التهاب', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('wet-wipes', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Дастмоли тар', 'Влажные салфетки', 'Wet Wipes', 'دستمال مرطوب', NULL, 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('body-cream', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Кремии бадан', 'Крем для тела', 'Body Cream', 'کرم بدن', NULL, 90, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('menstrual-cup', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Косаи ҳайз', 'Менструальная чаша', 'Menstrual Cup', 'کاپ قاعدگی', NULL, 100, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('cotton-buds', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Гӯшпоккунак', 'Ватные палочки', 'Cotton Buds', 'گوش‌پاک‌کن', NULL, 110, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hand-wash', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Моеъи дастшӯӣ', 'Жидкое мыло', 'Hand Wash', 'مایع دستشویی', NULL, 120, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hand-mask', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Ниқоби даст', 'Маска для рук', 'Hand Mask', 'ماسک دست', NULL, 130, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('foot-mask', (SELECT id FROM beauty_categories WHERE slug='body-care'), 3, 'personal-care', 'Ниқоби пой', 'Маска для ног', 'Foot Mask', 'ماسک پا', NULL, 140, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('oral-care', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Беҳдошти даҳон ва дандон', 'Гигиена полости рта', 'Oral Care', 'بهداشت دهان و دندان', 'sparkles', 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('toothbrush', (SELECT id FROM beauty_categories WHERE slug='oral-care'), 3, 'personal-care', 'Чӯткаи дандон', 'Зубная щётка', 'Toothbrush', 'مسواک', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('toothpaste', (SELECT id FROM beauty_categories WHERE slug='oral-care'), 3, 'personal-care', 'Хамираи дандон', 'Зубная паста', 'Toothpaste', 'خمیردندان', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mouthwash', (SELECT id FROM beauty_categories WHERE slug='oral-care'), 3, 'personal-care', 'Даҳоншӯй', 'Ополаскиватель', 'Mouthwash', 'دهان‌شویه', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('dental-floss', (SELECT id FROM beauty_categories WHERE slug='oral-care'), 3, 'personal-care', 'Ресмони дандон', 'Зубная нить', 'Dental Floss', 'نخ دندان', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('interdental-brush', (SELECT id FROM beauty_categories WHERE slug='oral-care'), 3, 'personal-care', 'Чӯткаи байнидандонӣ', 'Межзубный ёршик', 'Interdental Brush', 'براش بین‌دندانی', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('tongue-cleaner', (SELECT id FROM beauty_categories WHERE slug='oral-care'), 3, 'personal-care', 'Забонпоккунак', 'Скребок для языка', 'Tongue Cleaner', 'زبان‌پاک‌کن', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('shaving', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Ислоҳи рӯй ва бадан', 'Бритьё и депиляция', 'Shaving & Hair Removal', 'اصلاح صورت و بدن', 'edit', 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('wax', (SELECT id FROM beauty_categories WHERE slug='shaving'), 3, 'personal-care', 'Вакс', 'Воск', 'Wax', 'وکس', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('depilatory', (SELECT id FROM beauty_categories WHERE slug='shaving'), 3, 'personal-care', 'Нӯор ва маҳсулоти мӯбар', 'Депиляционные средства', 'Depilatories', 'نوار و محصولات موبر', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('aftershave', (SELECT id FROM beauty_categories WHERE slug='shaving'), 3, 'personal-care', 'Маҳсулоти баъд аз ислоҳ', 'Средства после бритья', 'Aftershave', 'محصولات بعد از اصلاح', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('razor', (SELECT id FROM beauty_categories WHERE slug='shaving'), 3, 'personal-care', 'Теғи ислоҳ', 'Бритва', 'Razor', 'تیغ اصلاح', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('hygiene-sets', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Маҷмӯаи маҳсулоти беҳдоштӣ', 'Гигиенические наборы', 'Hygiene Sets & Tools', 'ست محصولات بهداشتی', 'package', 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('care-accessories', (SELECT id FROM beauty_categories WHERE slug='hygiene-sets'), 3, 'personal-care', 'Лавозими ёрирасон', 'Аксессуары', 'Accessories', 'لوازم جانبی', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mask-tools', (SELECT id FROM beauty_categories WHERE slug='hygiene-sets'), 3, 'personal-care', 'Ниқоб ва лавозими корӣ', 'Маски и инструменты', 'Masks & Tools', 'ماسک و لوازم کاربردی', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('surface-sanitizer', (SELECT id FROM beauty_categories WHERE slug='hygiene-sets'), 3, 'personal-care', 'Дезинфексияи сатҳ', 'Дезинфекция поверхностей', 'Surface Sanitizer', 'ضدعفونی‌کننده سطوح', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('skincare-tools', (SELECT id FROM beauty_categories WHERE slug='hygiene-sets'), 3, 'personal-care', 'Асбоби нигоҳубини пӯст', 'Инструменты для ухода', 'Skincare Tools', 'ابزار مراقبت از پوست', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('spa-bath', (SELECT id FROM beauty_categories WHERE slug='hygiene-sets'), 3, 'personal-care', 'Спа ва ҳаммом', 'Спа и ванна', 'Spa & Bath', 'اسپا و حمام', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-care', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Маҳсулоти беҳдоштии мардона', 'Мужской уход', 'Men''s Care', 'محصولات پوستی و بهداشتی آقایان', 'user', 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-shaving', (SELECT id FROM beauty_categories WHERE slug='mens-care'), 3, 'personal-care', 'Ислоҳи рӯй ва бадан', 'Бритьё для мужчин', 'Shaving', 'اصلاح صورت و بدن', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-skincare', (SELECT id FROM beauty_categories WHERE slug='mens-care'), 3, 'personal-care', 'Нигоҳубини рӯй ва бадан', 'Уход за кожей', 'Face & Body Care', 'مراقبت از صورت و بدن', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-hair', (SELECT id FROM beauty_categories WHERE slug='mens-care'), 3, 'personal-care', 'Нигоҳубини мӯй', 'Уход за волосами', 'Hair Care', 'مراقبت مو', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mens-other', (SELECT id FROM beauty_categories WHERE slug='mens-care'), 3, 'personal-care', 'Дигар маҳсулоти беҳдоштӣ', 'Прочий уход', 'Other Men''s Care', 'سایر محصولات بهداشتی آقایان', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('baby-care', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Маҳсулоти кӯдак ва навзод', 'Детская гигиена', 'Baby & Infant', 'محصولات کودک و نوزاد', 'heart', 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('bottle-pacifier', (SELECT id FROM beauty_categories WHERE slug='baby-care'), 3, 'personal-care', 'Шиша ва эмизак', 'Бутылочки и соски', 'Bottles & Pacifiers', 'شیشه و پستانک', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('baby-bottle', (SELECT id FROM beauty_categories WHERE slug='baby-care'), 3, 'personal-care', 'Шишаи шир', 'Детская бутылочка', 'Baby Bottle', 'شیشه شیر', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('baby-hygiene', (SELECT id FROM beauty_categories WHERE slug='baby-care'), 3, 'personal-care', 'Лавозими беҳдоштии кӯдак', 'Детская гигиена', 'Baby Hygiene', 'لوازم بهداشتی کودک', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('baby-cleaners', (SELECT id FROM beauty_categories WHERE slug='baby-care'), 3, 'personal-care', 'Тозакунандаи лавозими кӯдак', 'Средства для мытья', 'Baby Item Cleaners', 'پاک‌کننده و شوینده لوازم کودک', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('baby-bath', (SELECT id FROM beauty_categories WHERE slug='baby-care'), 3, 'personal-care', 'Лавозими ҳаммоми кӯдак', 'Детская ванна', 'Baby Bath', 'لوازم حمام کودک', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('skin-hair-supplement', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Мукаммали пӯст ва мӯй', 'Добавки для кожи и волос', 'Skin & Hair Supplements', 'مکمل پوست و مو', 'pill', 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('skin-hair-drinks', (SELECT id FROM beauty_categories WHERE slug='skin-hair-supplement'), 3, 'personal-care', 'Нӯшокӣ ва мукаммалҳои пӯсту мӯй', 'Напитки и добавки', 'Beauty Drinks & Supplements', 'نوشیدنی و مکمل‌های پوست و مو', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('intimate', (SELECT id FROM beauty_categories WHERE slug='personal-care'), 2, 'personal-care', 'Маҳсулоти ҳамсарӣ ва ҷинсӣ', 'Интимные товары', 'Intimate & Sexual', 'محصولات زناشویی و جنسی', 'heart', 90, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('intimate-gel', (SELECT id FROM beauty_categories WHERE slug='intimate'), 3, 'personal-care', 'Гелҳои ҳамсарӣ', 'Интимные гели', 'Intimate Gels', 'ژل‌های زناشویی', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('condom', (SELECT id FROM beauty_categories WHERE slug='intimate'), 3, 'personal-care', 'Кондом', 'Презервативы', 'Condoms', 'کاندوم', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;
