-- migrations/12_parts/03_makeup.sql
-- Part 4 of 8 — run AFTER 00_schema.sql, in any order relative to
-- the other department files (this one only references its own rows).
-- GENERATED by scripts/split_beauty_tree_sql.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here.

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('makeup', NULL, 1, 'makeup', 'Маҳсулоти ороишӣ', 'Косметика (макияж)', 'Makeup', 'آرایشی', 'sparkles', 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-makeup', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Ороиши рӯй', 'Макияж лица', 'Face Makeup', 'آرایش صورت', 'star', 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('concealer', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Пинҳонкунак', 'Консилер', 'Concealer', 'کانسیلر', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('foundation', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Кремпудра', 'Тональный крем', 'Foundation', 'کرم‌پودر', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-primer', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Праймери рӯй', 'Праймер для лица', 'Face Primer', 'پرایمر صورت', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('powder', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Пудра ё панкейк', 'Пудра', 'Powder', 'پودر صورت یا پنکیک', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('contour-highlighter', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Контур ва ҳайлайтер', 'Контур и хайлайтер', 'Contour & Highlighter', 'کانتور و هایلایتر', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('setting-spray', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Фиксатори ороиш', 'Фиксатор макияжа', 'Setting Spray', 'فیکساتور آرایش', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('bb-cc-cream', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Кремҳои BB, CC ва DD', 'BB, CC и DD кремы', 'BB, CC & DD Creams', 'کرم‌های BB، CC و DD', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('blush', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Рӯгуна', 'Румяна', 'Blush', 'رژگونه', NULL, 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('bronzer', (SELECT id FROM beauty_categories WHERE slug='face-makeup'), 3, 'makeup', 'Бронзкунанда', 'Бронзатор', 'Bronzer', 'برنزه‌کننده', NULL, 90, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eye-makeup', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Ороиши чашм', 'Макияж глаз', 'Eye Makeup', 'آرایش چشم', 'eye', 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eye-primer', (SELECT id FROM beauty_categories WHERE slug='eye-makeup'), 3, 'makeup', 'Праймери чашм', 'Праймер для век', 'Eye Primer', 'پرایمر چشم', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eyeshadow', (SELECT id FROM beauty_categories WHERE slug='eye-makeup'), 3, 'makeup', 'Сояи чашм', 'Тени для век', 'Eyeshadow', 'سایه چشم', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eyeliner', (SELECT id FROM beauty_categories WHERE slug='eye-makeup'), 3, 'makeup', 'Хатти чашм', 'Подводка для глаз', 'Eyeliner', 'خط چشم', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eye-pencil', (SELECT id FROM beauty_categories WHERE slug='eye-makeup'), 3, 'makeup', 'Медади чашм', 'Карандаш для глаз', 'Eye Pencil', 'مداد چشم', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mascara', (SELECT id FROM beauty_categories WHERE slug='eye-makeup'), 3, 'makeup', 'Туш барои мижа', 'Тушь для ресниц', 'Mascara', 'ریمل', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brow-makeup', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Ороиши абрӯ', 'Макияж бровей', 'Brow Makeup', 'آرایش ابرو', 'edit', 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brow-pencil', (SELECT id FROM beauty_categories WHERE slug='brow-makeup'), 3, 'makeup', 'Медади абрӯ', 'Карандаш для бровей', 'Brow Pencil', 'مداد ابرو', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brow-powder', (SELECT id FROM beauty_categories WHERE slug='brow-makeup'), 3, 'makeup', 'Сояи абрӯ', 'Тени для бровей', 'Brow Powder', 'سایه ابرو', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brow-mascara', (SELECT id FROM beauty_categories WHERE slug='brow-makeup'), 3, 'makeup', 'Туши абрӯ', 'Тушь для бровей', 'Brow Mascara', 'ریمل ابرو', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brow-marker', (SELECT id FROM beauty_categories WHERE slug='brow-makeup'), 3, 'makeup', 'Маркери абрӯ', 'Маркер для бровей', 'Brow Marker', 'ماژیک ابرو', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('brow-gel', (SELECT id FROM beauty_categories WHERE slug='brow-makeup'), 3, 'makeup', 'Гели абрӯ', 'Гель для бровей', 'Brow Gel', 'ژل ابرو', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-makeup', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Ороиши лаб', 'Макияж губ', 'Lip Makeup', 'آرایش لب', 'heart', 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-primer', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Праймери лаб', 'Праймер для губ', 'Lip Primer', 'پرایمر لب', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lipstick', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Ранги лаб', 'Помада', 'Lipstick', 'رژ لب', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('liquid-lipstick', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Ранги лаби моеъ', 'Жидкая помада', 'Liquid Lipstick', 'رژ لب مایع', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-marker', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Маркери лаб', 'Маркер для губ', 'Lip Marker', 'ماژیک لب', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-liner', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Медади лаб', 'Карандаш для губ', 'Lip Liner', 'مداد لب', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-balm', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Балзами лаб', 'Бальзам для губ', 'Lip Balm', 'بالم لب', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-tint', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Тинти лаб', 'Тинт для губ', 'Lip Tint', 'تینت لب', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-oil', (SELECT id FROM beauty_categories WHERE slug='lip-makeup'), 3, 'makeup', 'Равғани лаб', 'Масло для губ', 'Lip Oil', 'روغن لب', NULL, 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('nail-makeup', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Ороиши нохун', 'Маникюр и ногти', 'Nail Makeup', 'آرایش ناخن', 'sparkles', 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('nail-polish', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Лок', 'Лак для ногтей', 'Nail Polish', 'لاک', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('base-coat', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Бейси нохун', 'База для ногтей', 'Base Coat', 'بیس ناخن', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('top-coat', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Топкот', 'Топовое покрытие', 'Top Coat', 'تاپ‌کت', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('nail-strengthener', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Мустаҳкамкунандаи нохун', 'Укрепитель ногтей', 'Nail Strengthener', 'تقویت‌کننده ناخن', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('nail-remover', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Локпоккунак', 'Жидкость для снятия лака', 'Nail Polish Remover', 'لاک‌پاک‌کن', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('manicure-tools', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Лавозими маникюр ва педикюр', 'Инструменты для маникюра', 'Manicure & Pedicure Tools', 'لوازم مانیکور و پدیکور', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('cuticle-care', (SELECT id FROM beauty_categories WHERE slug='nail-makeup'), 3, 'makeup', 'Маҳсулоти кутикула', 'Уход за кутикулой', 'Cuticle Care', 'محصولات کوتیکول، مانیکور و پدیکور', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('makeup-accessories', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Лавозими ёрирасони ороишӣ', 'Аксессуары для макияжа', 'Makeup Accessories', 'لوازم جانبی آرایشی', 'package', 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('mirror', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Оина', 'Зеркало', 'Mirror', 'آینه', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('sharpener', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Тарош', 'Точилка', 'Sharpener', 'تراش', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('tweezers', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Мӯчина', 'Пинцет', 'Tweezers', 'موچین', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-brush', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Фейс браш', 'Кисть для лица', 'Face Brush', 'فیس براش', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('makeup-brush', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Мӯйқалами ороишӣ', 'Кисть для макияжа', 'Makeup Brush', 'براش آرایشی', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('makeup-bag', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Кисаи ороишӣ', 'Косметичка', 'Makeup Bag', 'کیف آرایشی', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lashes', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Мижа ва часпаки мижа', 'Ресницы и клей', 'Lashes & Glue', 'مژه و چسب مژه', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('blender', (SELECT id FROM beauty_categories WHERE slug='makeup-accessories'), 3, 'makeup', 'Пад ва блендери ороишӣ', 'Спонж и бьютиблендер', 'Pad & Blender', 'پد و بلندر آرایشی', NULL, 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('makeup-sets', (SELECT id FROM beauty_categories WHERE slug='makeup'), 2, 'makeup', 'Маҷмӯаҳои ороишӣ', 'Наборы для макияжа', 'Makeup Sets', 'ست‌های آرایشی', 'package', 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('cleansing-pad', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Пад ва испанҷи тозакунанда', 'Очищающие спонжи', 'Cleansing Pads', 'پد و اسفنج پاک‌کننده', NULL, 10, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('beauty-box', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Бюти-бокс', 'Бьюти-бокс', 'Beauty Box', 'بیوتی باکس', NULL, 20, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('makeup-set', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Маҷмӯаи ороишӣ', 'Набор для макияжа', 'Makeup Set', 'ست آرایشی', NULL, 30, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('face-set', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Маҷмӯаи ороиши рӯй', 'Набор для лица', 'Face Set', 'ست آرایشی صورت', NULL, 40, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('eye-set', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Маҷмӯаи ороиши чашм', 'Набор для глаз', 'Eye Set', 'ست آرایشی چشم', NULL, 50, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('lip-set', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Маҷмӯаи ороиши лаб', 'Набор для губ', 'Lip Set', 'ست آرایشی لب', NULL, 60, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('nail-set', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Маҷмӯаи ороиши нохун', 'Набор для ногтей', 'Nail Set', 'ست آرایشی ناخن', NULL, 70, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;

INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES
  ('accessory-set', (SELECT id FROM beauty_categories WHERE slug='makeup-sets'), 3, 'makeup', 'Маҷмӯаи лавозими ороишӣ', 'Набор аксессуаров', 'Accessory Set', 'ست لوازم آرایشی جانبی', NULL, 80, true)
  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,
    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,
    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;
