// scripts/gen_beauty_tree.mjs
// Emits migrations/12_beauty_category_tree.sql (the whole tree, one file,
// idempotent, safe re-run) from the shared tree data in
// scripts/lib/beautyTreeData.mjs — edit the tree there, not here.
// For a version split into one file per department (handy for pasting into
// the Supabase SQL editor piece by piece), see scripts/split_beauty_tree_sql.mjs.
import { writeFileSync } from "node:fs";
import { TREE, OLD_SLUGS, q } from "./lib/beautyTreeData.mjs";

const rows = [];
const seen = new Set();
let count = 0;
const walk = (nodes, level, parentSlug, rootSlug) => {
  nodes.forEach((n, i) => {
    if (seen.has(n.slug)) throw new Error(`duplicate slug: ${n.slug}`);
    seen.add(n.slug);
    const root = level === 1 ? n.slug : rootSlug;
    const parentExpr = level === 1 ? "NULL" : `(SELECT id FROM beauty_categories WHERE slug=${q(parentSlug)})`;
    const iconExpr = n.icon ? q(n.icon) : "NULL";
    rows.push(
      `INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES\n` +
      `  (${q(n.slug)}, ${parentExpr}, ${level}, ${q(root)}, ${q(n.tg)}, ${q(n.ru)}, ${q(n.en)}, ${q(n.fa)}, ${iconExpr}, ${(i + 1) * 10}, true)\n` +
      `  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,\n` +
      `    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,\n` +
      `    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;`
    );
    count++;
    if (n.children) walk(n.children, level + 1, n.slug, root);
  });
};
walk(TREE, 1, null, null);

const sql = `-- migrations/12_beauty_category_tree.sql
-- Beauty 3-level category tree: department (7) -> group -> leaf, all locales.
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here.
-- Idempotent + safe to re-run. Run once in the Supabase SQL editor.
--
-- Verify after running:
--   SELECT level, COUNT(*) FROM beauty_categories GROUP BY level ORDER BY level;
--   SELECT slug, name_fa FROM beauty_categories WHERE parent_id IS NULL ORDER BY sort_order;

-- ── 1) schema: self-referencing tree ────────────────────────────────────────
ALTER TABLE beauty_categories
  ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES beauty_categories(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS level     INT NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_beauty_categories_parent ON beauty_categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_beauty_categories_level  ON beauty_categories (level);

-- ── 2) retire the old two-level starter seed (only rows with no products) ────
DELETE FROM beauty_categories
  WHERE slug IN (${OLD_SLUGS.map(q).join(", ")})
    AND id NOT IN (SELECT category_id FROM beauty_products WHERE category_id IS NOT NULL);

-- ── 3) the full tree (${count} nodes) — parents before children ──────────────
${rows.join("\n\n")}
`;

writeFileSync(new URL("../migrations/12_beauty_category_tree.sql", import.meta.url), sql);
console.log(`wrote migrations/12_beauty_category_tree.sql — ${count} categories`);
