// scripts/gen_beauty_tree.mjs
// Emits the Beauty 3-level category tree (7 departments → groups → leaves,
// all four locales) as 8 numbered migration files, continuing the repo's
// existing migrations/NN_description.sql numbering (last one before this was
// 11_beauty_brands.sql):
//   migrations/12_beauty_category_tree_schema.sql       — parent_id/level
//     columns + retiring the old two-level seed. RUN THIS ONE FIRST, ALONE.
//   migrations/13_beauty_category_tree_perfume.sql
//   migrations/14_beauty_category_tree_personal_care.sql
//   migrations/15_beauty_category_tree_makeup.sql
//   migrations/16_beauty_category_tree_hair.sql
//   migrations/17_beauty_category_tree_electrical.sql
//   migrations/18_beauty_category_tree_fashion.sql
//   migrations/19_beauty_category_tree_supplements.sql
// 13..19 are independent of each other (no department references another
// department's rows) — run them in any order, right after 12. Every INSERT
// uses ON CONFLICT (slug) DO UPDATE, so re-running any file is always safe.
//
// Edit the tree in scripts/lib/beautyTreeData.mjs, not here. Run:
//   node scripts/gen_beauty_tree.mjs
import { writeFileSync } from "node:fs";
import { TREE, OLD_SLUGS, q } from "./lib/beautyTreeData.mjs";

const OUT_DIR = new URL("../migrations/", import.meta.url);

const insertStmt = (n, level, parentSlug, rootSlug, i) => {
  const root = level === 1 ? n.slug : rootSlug;
  const parentExpr = level === 1 ? "NULL" : `(SELECT id FROM beauty_categories WHERE slug=${q(parentSlug)})`;
  const iconExpr = n.icon ? q(n.icon) : "NULL";
  return (
    `INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES\n` +
    `  (${q(n.slug)}, ${parentExpr}, ${level}, ${q(root)}, ${q(n.tg)}, ${q(n.ru)}, ${q(n.en)}, ${q(n.fa)}, ${iconExpr}, ${(i + 1) * 10}, true)\n` +
    `  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,\n` +
    `    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,\n` +
    `    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;`
  );
};

// Collects one department's own INSERT + every descendant's, depth-first.
const collect = (n, level, parentSlug, rootSlug, i, out) => {
  out.push(insertStmt(n, level, parentSlug, rootSlug, i));
  if (n.children) n.children.forEach((c, j) => collect(c, level + 1, n.slug, rootSlug, j, out));
};

// ── 12: schema + retire old seed — run this ONE first, alone ───────────────
const schemaSql = `-- migrations/12_beauty_category_tree_schema.sql
-- Beauty 3-level category tree, part 1 of 8 — RUN THIS FILE FIRST, ALONE.
-- Files 13..19 (one per department) depend on the columns this adds.
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here. Idempotent, safe to re-run.

ALTER TABLE beauty_categories
  ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES beauty_categories(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS level     INT NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_beauty_categories_parent ON beauty_categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_beauty_categories_level  ON beauty_categories (level);

-- Retire the old two-level starter seed (only rows with no products attached).
DELETE FROM beauty_categories
  WHERE slug IN (${OLD_SLUGS.map(q).join(", ")})
    AND id NOT IN (SELECT category_id FROM beauty_products WHERE category_id IS NOT NULL);
`;
writeFileSync(new URL("12_beauty_category_tree_schema.sql", OUT_DIR), schemaSql);
console.log("wrote migrations/12_beauty_category_tree_schema.sql");

// ── 13..19: one self-contained file per department ─────────────────────────
TREE.forEach((dept, idx) => {
  const out = [];
  collect(dept, 1, null, dept.slug, idx, out);
  const num = 13 + idx;
  const fname = `${num}_beauty_category_tree_${dept.slug.replace(/-/g, "_")}.sql`;
  const body = `-- migrations/${fname}
-- Beauty 3-level category tree, part ${idx + 2} of 8 — run AFTER
-- 12_beauty_category_tree_schema.sql, in any order relative to the other
-- department files (this one only references its own rows).
-- GENERATED by scripts/gen_beauty_tree.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here. Idempotent, safe to re-run.
--
-- Verify after running all 8 files:
--   SELECT level, COUNT(*) FROM beauty_categories GROUP BY level ORDER BY level;
--   SELECT slug, name_fa FROM beauty_categories WHERE parent_id IS NULL ORDER BY sort_order;

${out.join("\n\n")}
`;
  writeFileSync(new URL(fname, OUT_DIR), body);
  console.log(`wrote migrations/${fname} — ${out.length} categories`);
});
