// scripts/split_beauty_tree_sql.mjs
// Splits the migration 12 tree into one small file per department (plus one
// schema file), for pasting into the Supabase SQL editor piece by piece
// instead of one 1180-line block. Reads the same tree data as
// scripts/gen_beauty_tree.mjs (scripts/lib/beautyTreeData.mjs) — the combined
// migrations/12_beauty_category_tree.sql already has this data applied; this
// split is a convenience for re-running or reviewing it in smaller pieces.
//
// Run: node scripts/split_beauty_tree_sql.mjs
// Writes migrations/12_parts/00_schema.sql through 07_supplements.sql.
//
// Order that matters:
//   1. Run 00_schema.sql FIRST, alone (adds parent_id/level, retires the old seed).
//   2. Then run 01..07 in ANY order. Each department file only inserts its own
//      rows and references its own slugs — no department references another
//      — so they're independent: paste each into its own SQL editor tab and
//      run them back-to-back, or one after another, safely.
// Every INSERT uses ON CONFLICT (slug) DO UPDATE, so re-running any file is
// always safe and never duplicates rows.
import { writeFileSync, mkdirSync } from "node:fs";
import { TREE, OLD_SLUGS, q } from "./lib/beautyTreeData.mjs";

const OUT_DIR = new URL("../migrations/12_parts/", import.meta.url);
mkdirSync(OUT_DIR, { recursive: true });

const insertStmt = (n, level, parentSlug, rootSlug, i) => {
  const root = level === 1 ? n.slug : rootSlug;
  const parentExpr = level === 1 ? "NULL" : `(SELECT id FROM beauty_categories WHERE slug=${q(parentSlug)})`;
  const iconExpr = n.icon ? q(n.icon) : "NULL";
  return (
    `INSERT INTO beauty_categories (slug, parent_id, level, world, name_tg, name_ru, name_en, name_fa, icon, sort_order, is_active) VALUES\n` +
    `  (${q(n.slug)}, ${parentExpr}, ${level}, ${q(root)}, ${q(n.tg)}, ${q(n.ru)}, ${q(n.en)}, ${q(n.fa)}, ${iconExpr}, ${(i + 1) * 10}, true)\n` +
    `  ON CONFLICT (slug) DO UPDATE SET parent_id=EXCLUDED.parent_id, level=EXCLUDED.level, world=EXCLUDED.world,\n` +
    `    name_tg=EXCLUDED.name_tg, name_ru=EXCLUDED.name_ru, name_en=EXCLUDED.name_en, name_fa=EXCLUDED.name_fa,\n` +
    `    icon=EXCLUDED.icon, sort_order=EXCLUDED.sort_order;`
  );
};

// Collects one department's own INSERT + every descendant's, depth-first.
const collect = (n, level, parentSlug, rootSlug, i, out) => {
  out.push(insertStmt(n, level, parentSlug, rootSlug, i));
  if (n.children) n.children.forEach((c, j) => collect(c, level + 1, n.slug, rootSlug, j, out));
};

// ── 00: schema + retire old seed — run this ONE first, alone ───────────────
const schemaSql = `-- migrations/12_parts/00_schema.sql
-- Part 1 of 8 — RUN THIS FILE FIRST, ALONE. Everything in 01..07 depends on
-- the parent_id/level columns this adds.
-- GENERATED by scripts/split_beauty_tree_sql.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here.

ALTER TABLE beauty_categories
  ADD COLUMN IF NOT EXISTS parent_id BIGINT REFERENCES beauty_categories(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS level     INT NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_beauty_categories_parent ON beauty_categories (parent_id);
CREATE INDEX IF NOT EXISTS idx_beauty_categories_level  ON beauty_categories (level);

-- Retire the old two-level starter seed (only rows with no products attached).
DELETE FROM beauty_categories
  WHERE slug IN (${OLD_SLUGS.map(q).join(", ")})
    AND id NOT IN (SELECT category_id FROM beauty_products WHERE category_id IS NOT NULL);
`;
writeFileSync(new URL("00_schema.sql", OUT_DIR), schemaSql);
console.log("wrote migrations/12_parts/00_schema.sql");

// ── 01..07: one self-contained file per department ─────────────────────────
TREE.forEach((dept, idx) => {
  const out = [];
  collect(dept, 1, null, dept.slug, idx, out);
  const fname = `${String(idx + 1).padStart(2, "0")}_${dept.slug}.sql`;
  const body = `-- migrations/12_parts/${fname}
-- Part ${idx + 2} of 8 — run AFTER 00_schema.sql, in any order relative to
-- the other department files (this one only references its own rows).
-- GENERATED by scripts/split_beauty_tree_sql.mjs — edit the tree in
-- scripts/lib/beautyTreeData.mjs, not here.

${out.join("\n\n")}
`;
  writeFileSync(new URL(fname, OUT_DIR), body);
  console.log(`wrote migrations/12_parts/${fname} — ${out.length} categories`);
});
