// components/beauty/copy.js — Medoria Beauty copy, Tajik-first, mirroring the
// Health page structure (hero → values → worlds → featured → showcase → why →
// audience → quote → partnership → final CTA). ru/en match tg tone; fa = RTL.
export const BEAUTY_COPY = {
  tg: {
    nav: { collections: "Коллексия", worlds: "Самтҳо", partnership: "Ҳамкорӣ", contact: "Тамос", health: "Medoria Health", gateway: "Асосӣ" },
    hero: {
      eyebrow: "КОЛЛЕКСИЯИ ЛЮКСИ ЗЕБОӢ · B2B",
      h1a: "Зебоии люкс",
      h1b: "барои шарикони",
      h1c: "касбии шумо",
      sub: "Косметика, нигоҳубини пӯст ва абзорҳои зебоӣ — интихоби люкс барои салонҳо, бутикҳо ва мутахассисони Тоҷикистон.",
      chipsLabel: "Самтҳо:",
      ctaPrimary: "Дидани коллексия",
      ctaContact: "Тамос",
      trust: ["Брендҳои ҷаҳонӣ", "Расондан ба Тоҷикистон", "Шарики касбии шумо"],
      card: { region: "Luxury Beauty · Tajikistan", label: "Коллексияи мо", soon: "ба зудӣ", cta: "Дидани коллексия" },
    },
    values: [["Люкс", "стандарти интихоб"], ["Аслӣ", "брендҳои боэътимод"], ["3", "забони хизмат"], ["B2B", "шарикии касбӣ"]],
    worlds: {
      tag: "САМТҲО",
      h: "Се ҷаҳони зебоӣ",
      sub: "Ҳар самт — интихоби алоҳида бо ҳисси худ.",
      items: [
        { t: "Нигоҳубини пӯст", s: "Ритуали ҳаррӯза" },
        { t: "Ороиш", s: "Ранг ва ҷило" },
        { t: "Абзорҳои зебоӣ", s: "Ҷузъиёти люкс" },
      ],
      soon: "ба зудӣ",
    },
    featured: {
      tag: "ИНТИХОБИ МО",
      h: "Аз коллексияи аввал",
      sub: "Аввалин нигоҳ ба руҳияи Medoria Beauty.",
      items: [
        { t: "Ритуал", s: "Оғози нарми ҳар субҳ." },
        { t: "Дурахш", s: "Нуре, ки бо шумо мемонад." },
        { t: "Нафосат", s: "Ҷузъиёте, ки ҳис мешаванд." },
      ],
    },
    showcase: {
      tag: "ШИНОСОӢ — MEDORIA BEAUTY",
      h: "Аз витрина то салони шумо",
      sub: "Дар ин ҷо ба зудӣ расмҳои воқеии коллексия, бастабандӣ ва витринаи мо ҷойгир мешаванд.",
      tiles: ["Витринаи люкс", "Маҳсулоти аслӣ", "Бастабандии зебо", "Дастаи мо"],
      stat: "Расондан дар Тоҷикистон",
    },
    why: {
      tag: "БАРТАРИҲО",
      h: "Чаро Medoria Beauty?",
      items: [
        ["Интихоби люкс", "Ҳар маҳсулот аз рӯи сифат, ҳис ва эътимод интихоб мешавад — на аз рӯи рӯйхат."],
        ["Маҳсулоти аслӣ", "Танҳо брендҳо ва таъминкунандагони боэътимод."],
        ["Нархи касбӣ", "Шартҳои махсус барои салонҳо ва харидорони оптӣ."],
        ["Навигарии доимӣ", "Коллексия мунтазам нав мешавад."],
        ["Ҳамкории наздик", "Мушовара, намунаҳо ва дастгирии доимӣ."],
        ["Як бренд — ду ҷаҳон", "Эътимоди Medoria Health акнун дар зебоӣ."],
      ],
    },
    audience: {
      tag: "БАРОИ КӢ",
      items: [
        ["", "Салонҳои зебоӣ", "Коллексияи люкс ва расондани мунтазам барои салонҳо."],
        ["", "Бутикҳо ва дӯконҳо", "Витринаи зебо бо маҳсулоти аслӣ ва бастабандии хос."],
        ["", "Мутахассисони зебоӣ", "Абзор ва маводи касбӣ бо шартҳои махсус."],
      ],
    },
    quote: {
      q: "Ҳар маҳсулот — як лаҳзаи нур.",
      p: "Medoria Beauty — интихоби касбии зебоӣ аз оилаи Medoria.",
    },
    partnership: {
      tag: "ҲАМКОРИИ КАСБӢ",
      h: "Рӯйхати дархости худро бифиристед",
      sub: "Самтҳо ва брендҳои лозимаро нависед — мо прайс-лист, намунаҳо ва шартҳои ҳамкориро мефиристем.",
      benefits: [["bolt", "Ҷавоби зуд"], ["package", "Намунаҳо барои салонҳо"], ["truck", "Расондан ба Тоҷикистон"], ["badgeCheck", "Шартнома ва ҳисобнома"]],
      ph: "Дархости шумо…\n\nМисол:\nНигоҳубини пӯст — 10 ном\nОроиш — 15 ном\nАбзорҳо — 5 ном",
      org: "Салон / ташкилот",
      contact: "Телефон ё email",
      wa: "Фиристодан ба WhatsApp",
      tg: "Фиристодан ба Telegram",
      msgTitle: "Дархости ҳамкорӣ — Medoria Beauty",
      msgList: "Рӯйхат:",
    },
    finalCta: {
      tag: "ОМОДАИ ҲАМКОРӢ?",
      h: "Ҷаҳони зебоии Medoria-ро кашф кунед",
      sub: "Барои прайс-лист, намунаҳо ва шартҳои махсус ҳозир ба мо нависед.",
      wa: "Оғоз дар WhatsApp",
      tgm: "Оғоз дар Telegram",
    },
    footer: {
      desc: "Medoria Beauty — коллексияи люкси косметика ва нигоҳубин барои шарикони касбии Тоҷикистон.",
      colCollection: "Коллексия",
      colCompany: "Ширкат",
      colContact: "Тамос",
      copy: "© Medoria. Ҳамаи ҳуқуқҳо ҳифз шудаанд.",
    },
    marquee: ["Нигоҳубин", "Ороиш", "Дурахш", "Нафосат", "Люкс"],
  },
  ru: {
    nav: { collections: "Коллекция", worlds: "Направления", partnership: "Сотрудничество", contact: "Контакт", health: "Medoria Health", gateway: "Главная" },
    hero: {
      eyebrow: "ЛЮКСОВАЯ БЬЮТИ-КОЛЛЕКЦИЯ · B2B",
      h1a: "Люксовая красота",
      h1b: "для ваших",
      h1c: "профессионалов",
      sub: "Косметика, уход и бьюти-инструменты — люксовый отбор для салонов, бутиков и специалистов Таджикистана.",
      chipsLabel: "Направления:",
      ctaPrimary: "Смотреть коллекцию",
      ctaContact: "Связаться",
      trust: ["Мировые бренды", "Доставка по Таджикистану", "Ваш профессиональный партнёр"],
      card: { region: "Luxury Beauty · Tajikistan", label: "Наша коллекция", soon: "скоро", cta: "Смотреть коллекцию" },
    },
    values: [["Люкс", "стандарт отбора"], ["Оригинал", "проверенные бренды"], ["3", "языка сервиса"], ["B2B", "профессиональное партнёрство"]],
    worlds: {
      tag: "НАПРАВЛЕНИЯ",
      h: "Три мира красоты",
      sub: "Каждое направление — отдельный отбор со своим характером.",
      items: [
        { t: "Уход за кожей", s: "Ежедневный ритуал" },
        { t: "Макияж", s: "Цвет и сияние" },
        { t: "Бьюти-инструменты", s: "Детали люкса" },
      ],
      soon: "скоро",
    },
    featured: {
      tag: "НАШ ВЫБОР",
      h: "Из первой коллекции",
      sub: "Первый взгляд на настроение Medoria Beauty.",
      items: [
        { t: "Ритуал", s: "Мягкое начало каждого утра." },
        { t: "Сияние", s: "Свет, который остаётся с вами." },
        { t: "Изящество", s: "Детали, которые чувствуются." },
      ],
    },
    showcase: {
      tag: "ЗНАКОМЬТЕСЬ — MEDORIA BEAUTY",
      h: "От витрины до вашего салона",
      sub: "Здесь скоро появятся реальные фото коллекции, упаковки и витрины.",
      tiles: ["Люксовая витрина", "Оригинальные товары", "Красивая упаковка", "Наша команда"],
      stat: "Доставка по Таджикистану",
    },
    why: {
      tag: "ПРЕИМУЩЕСТВА",
      h: "Почему Medoria Beauty?",
      items: [
        ["Люксовый отбор", "Каждый продукт отбирается по качеству, чувству и доверию — не по списку."],
        ["Оригинальные товары", "Только проверенные бренды и поставщики."],
        ["Профессиональные цены", "Особые условия для салонов и оптовых закупок."],
        ["Постоянные новинки", "Коллекция регулярно обновляется."],
        ["Близкое партнёрство", "Консультации, образцы и постоянная поддержка."],
        ["Один бренд — два мира", "Доверие Medoria Health теперь и в красоте."],
      ],
    },
    audience: {
      tag: "ДЛЯ КОГО",
      items: [
        ["", "Салоны красоты", "Люксовая коллекция и регулярные поставки для салонов."],
        ["", "Бутики и магазины", "Красивая витрина с оригинальными продуктами."],
        ["", "Бьюти-специалисты", "Профессиональные инструменты на особых условиях."],
      ],
    },
    quote: {
      q: "Каждый продукт — мгновение света.",
      p: "Medoria Beauty — профессиональный выбор красоты из семьи Medoria.",
    },
    partnership: {
      tag: "ПРОФЕССИОНАЛЬНОЕ СОТРУДНИЧЕСТВО",
      h: "Отправьте нам ваш запрос",
      sub: "Напишите нужные направления и бренды — пришлём прайс-лист, образцы и условия сотрудничества.",
      benefits: [["bolt", "Быстрый ответ"], ["package", "Образцы для салонов"], ["truck", "Доставка по Таджикистану"], ["badgeCheck", "Договор и счёт"]],
      ph: "Ваш запрос…\n\nНапример:\nУход за кожей — 10 позиций\nМакияж — 15 позиций\nИнструменты — 5 позиций",
      org: "Салон / организация",
      contact: "Телефон или email",
      wa: "Отправить в WhatsApp",
      tg: "Отправить в Telegram",
      msgTitle: "Запрос на сотрудничество — Medoria Beauty",
      msgList: "Список:",
    },
    finalCta: {
      tag: "ГОТОВЫ К СОТРУДНИЧЕСТВУ?",
      h: "Откройте мир красоты Medoria",
      sub: "Напишите нам за прайс-листом, образцами и особыми условиями.",
      wa: "Начать в WhatsApp",
      tgm: "Начать в Telegram",
    },
    footer: {
      desc: "Medoria Beauty — люксовая коллекция косметики и ухода для профессиональных партнёров Таджикистана.",
      colCollection: "Коллекция",
      colCompany: "Компания",
      colContact: "Контакт",
      copy: "© Medoria. Все права защищены.",
    },
    marquee: ["Уход", "Макияж", "Сияние", "Изящество", "Люкс"],
  },
  en: {
    nav: { collections: "Collection", worlds: "Worlds", partnership: "Partnership", contact: "Contact", health: "Medoria Health", gateway: "Gateway" },
    hero: {
      eyebrow: "LUXURY BEAUTY COLLECTION · B2B",
      h1a: "Luxury beauty",
      h1b: "for your",
      h1c: "professionals",
      sub: "Cosmetics, skincare and beauty tools — a luxe selection for salons, boutiques and professionals across Tajikistan.",
      chipsLabel: "Worlds:",
      ctaPrimary: "View the collection",
      ctaContact: "Get in touch",
      trust: ["World brands", "Delivery across Tajikistan", "Your professional partner"],
      card: { region: "Luxury Beauty · Tajikistan", label: "Our collection", soon: "soon", cta: "View the collection" },
    },
    values: [["Luxe", "selection standard"], ["Original", "trusted brands"], ["3", "service languages"], ["B2B", "professional partnership"]],
    worlds: {
      tag: "WORLDS",
      h: "Three worlds of beauty",
      sub: "Each world is its own curation with its own character.",
      items: [
        { t: "Skincare", s: "A daily ritual" },
        { t: "Makeup", s: "Colour and glow" },
        { t: "Beauty Tools", s: "Details of luxe" },
      ],
      soon: "soon",
    },
    featured: {
      tag: "OUR PICKS",
      h: "From the first collection",
      sub: "A first look at the mood of Medoria Beauty.",
      items: [
        { t: "Ritual", s: "A soft start to every morning." },
        { t: "Radiance", s: "Light that stays with you." },
        { t: "Elegance", s: "Details you can feel." },
      ],
    },
    showcase: {
      tag: "MEET MEDORIA BEAUTY",
      h: "From our display to your salon",
      sub: "Real photos of the collection, packaging and display will live here soon.",
      tiles: ["Luxe display", "Original products", "Beautiful packaging", "Our team"],
      stat: "Delivery across Tajikistan",
    },
    why: {
      tag: "WHY US",
      h: "Why Medoria Beauty?",
      items: [
        ["Luxe curation", "Every product is chosen for quality, feeling and trust — not by list."],
        ["Original products", "Only trusted brands and suppliers."],
        ["Professional pricing", "Special terms for salons and wholesale."],
        ["Always new", "The collection refreshes regularly."],
        ["Close partnership", "Consultation, samples and ongoing support."],
        ["One brand, two worlds", "The trust of Medoria Health, now in beauty."],
      ],
    },
    audience: {
      tag: "WHO IT IS FOR",
      items: [
        ["", "Beauty salons", "A luxe collection and regular supply for salons."],
        ["", "Boutiques and stores", "A beautiful display of original products."],
        ["", "Beauty professionals", "Professional tools on special terms."],
      ],
    },
    quote: {
      q: "Every product is a moment of light.",
      p: "Medoria Beauty is the professional choice in beauty from the Medoria family.",
    },
    partnership: {
      tag: "PROFESSIONAL PARTNERSHIP",
      h: "Send us your request",
      sub: "Tell us the worlds and brands you need — we will send the price list, samples and partnership terms.",
      benefits: [["bolt", "Fast reply"], ["package", "Samples for salons"], ["truck", "Delivery across Tajikistan"], ["badgeCheck", "Contract and invoice"]],
      ph: "Your request…\n\nExample:\nSkincare — 10 items\nMakeup — 15 items\nTools — 5 items",
      org: "Salon / organization",
      contact: "Phone or email",
      wa: "Send to WhatsApp",
      tg: "Send to Telegram",
      msgTitle: "Partnership request — Medoria Beauty",
      msgList: "List:",
    },
    finalCta: {
      tag: "READY TO PARTNER?",
      h: "Discover the Medoria world of beauty",
      sub: "Write to us for the price list, samples and special terms.",
      wa: "Start on WhatsApp",
      tgm: "Start on Telegram",
    },
    footer: {
      desc: "Medoria Beauty is a luxe collection of cosmetics and care for professional partners across Tajikistan.",
      colCollection: "Collection",
      colCompany: "Company",
      colContact: "Contact",
      copy: "© Medoria. All rights reserved.",
    },
    marquee: ["Skincare", "Makeup", "Radiance", "Elegance", "Luxe"],
  },
  fa: {
    nav: { collections: "کالکشن", worlds: "دنیاها", partnership: "همکاری", contact: "تماس", health: "مدوریا هلث", gateway: "صفحه اصلی" },
    hero: {
      eyebrow: "کالکشن لوکس زیبایی · B2B",
      h1a: "زیبایی لوکس",
      h1b: "برای شرکای",
      h1c: "حرفه‌ای شما",
      sub: "آرایشی، مراقبت پوست و ابزار زیبایی — انتخابی لوکس برای سالن‌ها، بوتیک‌ها و متخصصان.",
      chipsLabel: "دنیاها:",
      ctaPrimary: "دیدن کالکشن",
      ctaContact: "تماس",
      trust: ["برندهای جهانی", "ارسال سراسری", "شریک حرفه‌ای شما"],
      card: { region: "Luxury Beauty · Tajikistan", label: "کالکشن ما", soon: "به‌زودی", cta: "دیدن کالکشن" },
    },
    values: [["لوکس", "استاندارد انتخاب"], ["اصل", "برندهای معتبر"], ["۳", "زبان خدمات"], ["B2B", "همکاری حرفه‌ای"]],
    worlds: {
      tag: "دنیاها",
      h: "سه دنیای زیبایی",
      sub: "هر دنیا انتخابی جدا با حس خودش.",
      items: [
        { t: "مراقبت پوست", s: "آیین روزانه" },
        { t: "آرایش", s: "رنگ و درخشش" },
        { t: "ابزار زیبایی", s: "جزئیات لوکس" },
      ],
      soon: "به‌زودی",
    },
    featured: {
      tag: "انتخاب ما",
      h: "از نخستین کالکشن",
      sub: "نگاه نخست به حال‌وهوای مدوریا بیوتی.",
      items: [
        { t: "آیین", s: "آغازی نرم برای هر صبح." },
        { t: "درخشش", s: "نوری که با شما می‌ماند." },
        { t: "ظرافت", s: "جزئیاتی که حس می‌شوند." },
      ],
    },
    showcase: {
      tag: "آشنایی — مدوریا بیوتی",
      h: "از ویترین تا سالن شما",
      sub: "به‌زودی عکس‌های واقعی کالکشن و بسته‌بندی اینجا قرار می‌گیرد.",
      tiles: ["ویترین لوکس", "محصولات اصل", "بسته‌بندی زیبا", "تیم ما"],
      stat: "ارسال سراسری",
    },
    why: {
      tag: "مزیت‌ها",
      h: "چرا مدوریا بیوتی؟",
      items: [
        ["انتخاب لوکس", "هر محصول بر پایه کیفیت، حس و اعتماد انتخاب می‌شود."],
        ["محصولات اصل", "فقط برندها و تأمین‌کنندگان معتبر."],
        ["قیمت حرفه‌ای", "شرایط ویژه برای سالن‌ها و خرید عمده."],
        ["تازگی همیشگی", "کالکشن مرتب به‌روز می‌شود."],
        ["همکاری نزدیک", "مشاوره، نمونه و پشتیبانی مستمر."],
        ["یک برند — دو دنیا", "اعتماد مدوریا هلث حالا در زیبایی."],
      ],
    },
    audience: {
      tag: "برای چه کسانی",
      items: [
        ["", "سالن‌های زیبایی", "کالکشن لوکس و تأمین منظم برای سالن‌ها."],
        ["", "بوتیک‌ها و فروشگاه‌ها", "ویترینی زیبا با محصولات اصل."],
        ["", "متخصصان زیبایی", "ابزار حرفه‌ای با شرایط ویژه."],
      ],
    },
    quote: { q: "هر محصول، لحظه‌ای از نور است.", p: "مدوریا بیوتی، انتخاب حرفه‌ای زیبایی از خانواده مدوریا." },
    partnership: {
      tag: "همکاری حرفه‌ای",
      h: "درخواست خود را بفرستید",
      sub: "دنیاها و برندهای موردنیازتان را بنویسید — پرایس‌لیست، نمونه و شرایط همکاری را می‌فرستیم.",
      benefits: [["bolt", "پاسخ سریع"], ["package", "نمونه برای سالن‌ها"], ["truck", "ارسال سراسری"], ["badgeCheck", "قرارداد و فاکتور"]],
      ph: "درخواست شما…",
      org: "سالن / سازمان",
      contact: "تلفن یا ایمیل",
      wa: "ارسال به واتساپ",
      tg: "ارسال به تلگرام",
      msgTitle: "درخواست همکاری — مدوریا بیوتی",
      msgList: "لیست:",
    },
    finalCta: {
      tag: "آماده همکاری؟",
      h: "دنیای زیبایی مدوریا را کشف کنید",
      sub: "برای پرایس‌لیست، نمونه‌ها و شرایط ویژه به ما پیام دهید.",
      wa: "شروع در واتساپ",
      tgm: "شروع در تلگرام",
    },
    footer: {
      desc: "مدوریا بیوتی — کالکشن لوکس آرایشی و مراقبتی برای شرکای حرفه‌ای.",
      colCollection: "کالکشن",
      colCompany: "شرکت",
      colContact: "تماس",
      copy: "© مدوریا. همه حقوق محفوظ است.",
    },
    marquee: ["مراقبت", "آرایش", "درخشش", "ظرافت", "لوکس"],
  },
};

export function beautyCopy(lang) {
  return BEAUTY_COPY[lang] || BEAUTY_COPY.en;
}
